//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccCashSettlement
    {
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal FinYear { get; set; }
        public System.DateTime DocDate { get; set; }
        public decimal AccountMGroups_UID { get; set; }
        public Nullable<decimal> Dr { get; set; }
        public Nullable<decimal> Cr { get; set; }
        public Nullable<decimal> ExcessAmount { get; set; }
        public Nullable<decimal> ShortageAmount { get; set; }
        public Nullable<decimal> SuspenseAmount { get; set; }
    }
}
