//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMPartnersAddress
    {
        public decimal UID { get; set; }
        public decimal AccountM_UID { get; set; }
        public string PartnerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string PinCode { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Floor { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string Landmark { get; set; }
        public Nullable<decimal> AreaMaster_UID { get; set; }
        public System.DateTime CreatededDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
