//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMItemsBOM
    {
        public decimal UID { get; set; }
        public decimal AccountMItems_UID { get; set; }
        public decimal AccountMItems_UsedItem_UID { get; set; }
        public decimal QtyReq { get; set; }
        public decimal QtyPer { get; set; }
        public int CurrentStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
