//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMPartner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountMPartner()
        {
            this.AccountMPartners_CardMaster = new HashSet<AccountMPartners_CardMaster>();
            this.AccountMPartners_Extn = new HashSet<AccountMPartners_Extn>();
        }
    
        public decimal UID { get; set; }
        public decimal AccountM_UID { get; set; }
        public int PartnerType { get; set; }
        public string PartnerCode { get; set; }
        public string PartnerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string PinCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string TINNo { get; set; }
        public string TINDate { get; set; }
        public string CSTNo { get; set; }
        public string CSTDate { get; set; }
        public string PANNo { get; set; }
        public decimal DebitCreditLimit { get; set; }
        public bool IsTDS { get; set; }
        public bool IsSalesTax { get; set; }
        public bool IsLocal { get; set; }
        public decimal Default_PriceList_UID { get; set; }
        public bool IsApproved { get; set; }
        public decimal CurrencyM_UID { get; set; }
        public string LongPartnerName { get; set; }
        public bool IsHoldForOrder { get; set; }
        public string IsHoldForOrderReason { get; set; }
        public bool IsHoldForPayment { get; set; }
        public string IsHoldForPaymentReason { get; set; }
        public decimal TaxTypeId { get; set; }
        public decimal DefaultAccountMGroups_UID { get; set; }
        public bool IsDebitCreditLimitApplicable { get; set; }
        public bool IsDebitCreditDaysApplicable { get; set; }
        public int DebitCreditDays { get; set; }
        public decimal TDSTypeId { get; set; }
        public int SurchargePer { get; set; }
        public bool IsCompany { get; set; }
        public decimal State_UID { get; set; }
        public decimal PaymentDay_UID { get; set; }
        public string InFavourOf { get; set; }
        public decimal Country_UID { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Floor { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string Landmark { get; set; }
        public string CardKey { get; set; }
        public Nullable<decimal> AreaMaster_UID { get; set; }
    
        public virtual AccountM AccountM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountMPartners_CardMaster> AccountMPartners_CardMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountMPartners_Extn> AccountMPartners_Extn { get; set; }
    }
}
