//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMItems_DiscountMapping
    {
        public decimal UID { get; set; }
        public decimal AccountMItems_UID { get; set; }
        public bool IsDiscountByPer { get; set; }
        public decimal Discount { get; set; }
        public System.DateTime DateofExpiry { get; set; }
        public bool IsAvail { get; set; }
        public bool DateOfExpiryNeeded { get; set; }
        public string DiscountDescription { get; set; }
    
        public virtual AccountMItem AccountMItem { get; set; }
    }
}
