//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMItems_ImageMapping
    {
        public decimal UID { get; set; }
        public decimal AccountMItems_UID { get; set; }
        public string ItemImageName { get; set; }
        public string ItemLanguageName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> OrderNo { get; set; }
        public string ItemPrintName { get; set; }
        public string ItemImageFilePath { get; set; }
    }
}
