//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMItemsList
    {
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal AccountMGroups_UID { get; set; }
        public decimal AccountMItems_UID { get; set; }
        public decimal QOH { get; set; }
        public decimal ROL { get; set; }
        public decimal MOQ { get; set; }
        public decimal MaximumOrderQty { get; set; }
        public decimal ConQty_PerDay { get; set; }
        public string Location { get; set; }
        public string ABC { get; set; }
        public int IsInspectionRequired { get; set; }
        public decimal PriceList_Sales_UID { get; set; }
        public decimal PriceList_Purchase_UID { get; set; }
        public decimal CurrentRate { get; set; }
        public decimal WIP_AccountM_UID { get; set; }
        public decimal Sales_AccountM_UID { get; set; }
        public decimal Purchase_AccountM_UID { get; set; }
        public decimal Consumption_AccountM_UID { get; set; }
        public decimal Scrap_AccountM_UID { get; set; }
        public decimal Avgprice { get; set; }
        public decimal Tolerance { get; set; }
        public decimal LeadTime { get; set; }
        public bool IsReferred { get; set; }
        public decimal PurVAT_AccountM_UID { get; set; }
        public decimal PurCST_AccountM_UID { get; set; }
        public decimal SalVAT_AccountM_UID { get; set; }
        public decimal SalCST_AccountM_UID { get; set; }
        public decimal Excise_AccountM_UID { get; set; }
        public decimal LastReceiptList_UID { get; set; }
    }
}
