//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountM_CardDetails
    {
        public decimal UID { get; set; }
        public decimal AccountMUID { get; set; }
        public decimal CardTypeUID { get; set; }
        public string CardNo { get; set; }
        public string CardHolderName { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string Remarks { get; set; }
        public string CharAttribute1 { get; set; }
        public string StringAttribute1 { get; set; }
        public string StringAttribute2 { get; set; }
        public string StringAttribute3 { get; set; }
        public int NumberAttribute1 { get; set; }
        public int NumberAttribute2 { get; set; }
        public decimal NumberAttribute3 { get; set; }
        public decimal UIDAttribute1 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CardKey { get; set; }
    }
}
