//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMPartnersContact
    {
        public decimal UID { get; set; }
        public decimal AccountMPartners_UID { get; set; }
        public string ContactName { get; set; }
        public string Designation { get; set; }
        public string ContactNumber { get; set; }
        public string EMail { get; set; }
    }
}
