//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountM_CardDetailsList
    {
        public decimal UID { get; set; }
        public decimal AccountM_CardDetailsUID { get; set; }
        public Nullable<System.DateTime> ValidFromDateCrLimit { get; set; }
        public Nullable<System.DateTime> ValidToDateCrLimit { get; set; }
        public decimal CrLimit { get; set; }
        public decimal TotalAmountSpent { get; set; }
        public decimal BalanceAmount { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
