//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMPartners_CardMaster
    {
        public decimal UID { get; set; }
        public decimal AccountMPartners_UID { get; set; }
        public decimal CardNo { get; set; }
        public string CardType { get; set; }
        public string ValidityType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual AccountMPartner AccountMPartner { get; set; }
    }
}
