//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountM_CardDetails_History
    {
        public decimal UID { get; set; }
        public decimal AccountM_CardDetailsListUID { get; set; }
        public System.DateTime Recharge_Date { get; set; }
        public decimal User_UID { get; set; }
        public decimal CreditAmount { get; set; }
        public decimal TotalAmountSpend { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal BalanceAmt { get; set; }
    }
}
