//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccTrans_SqlLiteLink
    {
        public decimal UID { get; set; }
        public decimal AccTrans_UID { get; set; }
        public decimal SqlLiteAccountTrans_UID { get; set; }
        public System.Guid DeviceGUID { get; set; }
        public decimal Branch_UID { get; set; }
    }
}
