//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccTransListMatch
    {
        public decimal UID { get; set; }
        public decimal AccTransList_UID { get; set; }
        public decimal RefAccTransList_UID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public decimal TransListCostCenterM_UID { get; set; }
    }
}
