//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccTransDocument
    {
        public decimal UID { get; set; }
        public decimal AccTrans_UID { get; set; }
        public decimal ModeTypeM_UID { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string ReceivedFrom { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string PinCode { get; set; }
        public string Phone { get; set; }
        public string PrintDescription { get; set; }
        public decimal ChequeMList_UID { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
