//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaMaster
    {
        public decimal UID { get; set; }
        public string Description { get; set; }
        public int Estimate_Hour { get; set; }
        public int Estimate_Minutes { get; set; }
        public System.TimeSpan Estimate_Time { get; set; }
    }
}
