//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTransList_DiscountList_SQLite
    {
        public decimal UID { get; set; }
        public decimal BillTransList_SQLiteUID { get; set; }
        public decimal BillTransList_DiscountListUID { get; set; }
        public decimal BillProductID { get; set; }
        public decimal DiscountPer { get; set; }
        public decimal DiscountAmt { get; set; }
        public string DiscountDescription { get; set; }
        public decimal ProductID { get; set; }
        public decimal MainBillProductID { get; set; }
        public decimal MainBillTransList_SQLiteUID { get; set; }
    }
}
