//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTransOrderInfo_SQLite
    {
        public decimal UID { get; set; }
        public decimal BillTrans_SQLiteUID { get; set; }
        public decimal ServiceOrderInfoID { get; set; }
        public decimal BillID { get; set; }
        public decimal PartnerID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string DeliveryAddress1 { get; set; }
        public string DeliveryAddress2 { get; set; }
        public string DeliveryAddress3 { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> AdvanceAmt { get; set; }
        public Nullable<int> IsHomeDelivery { get; set; }
        public Nullable<decimal> DeliveryBoyID { get; set; }
        public Nullable<int> IsDelivered { get; set; }
        public string DeliveryUpdateDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string MobileNo { get; set; }
        public string CusName { get; set; }
        public string AddFloor { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string Landmark { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string PinCode { get; set; }
    
        public virtual BillTrans_SQLite BillTrans_SQLite { get; set; }
    }
}
