//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTransList_StockTransList_Link
    {
        public decimal BranchId { get; set; }
        public decimal BillTransList_UID { get; set; }
        public decimal StockTransList_UID { get; set; }
    }
}
