//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTransList_SQLite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillTransList_SQLite()
        {
            this.BillTransList_AddOnsList_SQLite = new HashSet<BillTransList_AddOnsList_SQLite>();
        }
    
        public decimal UID { get; set; }
        public decimal BillTrans_SQLiteUID { get; set; }
        public decimal BillProductID { get; set; }
        public decimal BillID { get; set; }
        public decimal ProductID { get; set; }
        public int OrderSequence { get; set; }
        public decimal OrderQty { get; set; }
        public decimal BillQty { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<System.DateTime> DeliverTime { get; set; }
        public decimal ProductPrice { get; set; }
        public decimal BillTotalAmount { get; set; }
        public decimal BillNetAmount { get; set; }
        public string SpecialInfo { get; set; }
        public string AddlInfo { get; set; }
        public decimal BillProductStatusID { get; set; }
        public decimal UOMID { get; set; }
        public int StockUpdated { get; set; }
        public decimal PendingUpdateQty { get; set; }
        public decimal ContainerAmount { get; set; }
        public decimal VatUID { get; set; }
        public string VatDescription { get; set; }
        public bool IsParcelItem { get; set; }
        public bool IsComplement { get; set; }
        public decimal ContainerM_UID { get; set; }
        public Nullable<int> IsAddon { get; set; }
        public Nullable<int> AddonAmountType { get; set; }
        public Nullable<int> IsServiceItem { get; set; }
        public Nullable<decimal> TimeMasterUID { get; set; }
        public string TimeMasterDesc { get; set; }
        public Nullable<decimal> FoodType { get; set; }
        public Nullable<System.DateTime> ValidFromDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<decimal> SubGroup_UID { get; set; }
        public string SubGroupName { get; set; }
        public string DineGroupName { get; set; }
        public Nullable<int> NotificationStatus { get; set; }
        public string ProductName { get; set; }
        public string UOMDesc { get; set; }
    
        public virtual BillTrans_SQLite BillTrans_SQLite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillTransList_AddOnsList_SQLite> BillTransList_AddOnsList_SQLite { get; set; }
    }
}
