//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTrans_Extn
    {
        public decimal UID { get; set; }
        public decimal BillTrans_UID { get; set; }
        public int BillFromType { get; set; }
        public decimal DiscountPer { get; set; }
        public decimal AdditionalAmount { get; set; }
        public string AdditionalAmountDesc { get; set; }
        public decimal ServiceCharge_ByPer { get; set; }
        public string OtherCharges_Desc1 { get; set; }
        public decimal OtherCharges_ByPer1 { get; set; }
        public decimal OtherCharges_ByAmount1 { get; set; }
        public decimal OtherCharges_Amount1 { get; set; }
        public string OtherCharges_Desc2 { get; set; }
        public decimal OtherCharges_ByPer2 { get; set; }
        public decimal OtherCharges_ByAmount2 { get; set; }
        public decimal OtherCharges_Amount2 { get; set; }
        public string ServiceTaxOnCharge_Desc { get; set; }
        public decimal ServiceTaxOnCharge_ByPer { get; set; }
        public decimal ServiceTaxOnCharge_ByAmount { get; set; }
        public decimal ServiceTaxOnCharge_Amount { get; set; }
        public decimal OtherCharges_UID1 { get; set; }
        public decimal OtherCharges_UID2 { get; set; }
        public decimal ServiceTaxOnCharge_UID { get; set; }
        public decimal NumberAttribute1 { get; set; }
        public decimal NumberAttribute2 { get; set; }
        public decimal NumberAttribute3 { get; set; }
        public string StringAttribute1 { get; set; }
        public string StringAttribute2 { get; set; }
        public Nullable<decimal> Customer_UID { get; set; }
        public Nullable<decimal> Card_UID { get; set; }
        public Nullable<decimal> Room_UID { get; set; }
        public decimal BillTrans_SQLiteUID { get; set; }
        public int OrderType { get; set; }
        public decimal CustomerAddress_UID { get; set; }
        public Nullable<System.Guid> PartitionKey { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public decimal DiscountM_UID { get; set; }
        public string DiscountDesc { get; set; }
    }
}
