//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTransList_IsDeliveredList
    {
        public decimal UID { get; set; }
        public decimal BillTransList_UID { get; set; }
        public bool IsDelivered { get; set; }
        public Nullable<System.DateTime> OrderdTime { get; set; }
        public Nullable<System.DateTime> PreparedTime { get; set; }
        public Nullable<System.DateTime> DeliverdTime { get; set; }
        public Nullable<decimal> StatusM_UID { get; set; }
        public Nullable<decimal> Captain_UID { get; set; }
        public Nullable<decimal> Waiter_UID { get; set; }
        public string ChefName { get; set; }
        public Nullable<decimal> Chef_UID { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public Nullable<decimal> BillTransList_SQLiteUID { get; set; }
        public Nullable<decimal> ExtendedPrepareTime { get; set; }
        public Nullable<decimal> TimeMasterUID { get; set; }
        public Nullable<System.DateTime> ValidFromDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
    }
}
