//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTrans_CalculationSQLite
    {
        public decimal UID { get; set; }
        public decimal BillTransSQLite_UID { get; set; }
        public decimal ConfigID { get; set; }
        public decimal ConfigType { get; set; }
        public string Description { get; set; }
        public decimal Percentage { get; set; }
        public decimal Amount { get; set; }
        public decimal Value { get; set; }
    }
}
