//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTrans_Extn_SQlite
    {
        public decimal UID { get; set; }
        public decimal BillTrans_SQLiteUID { get; set; }
        public decimal BillID { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal ServiceTax_UID { get; set; }
        public decimal ServiceTaxPer { get; set; }
        public decimal ServiceTaxAmount { get; set; }
        public decimal DiscountPer { get; set; }
        public decimal Discount { get; set; }
        public decimal ParcelCharge { get; set; }
        public decimal ACCharge { get; set; }
        public decimal SurchargeAmount { get; set; }
        public decimal RoundOff { get; set; }
        public string AdditionalAmountDesc { get; set; }
        public decimal AdditionalAmount { get; set; }
        public decimal ServiceTaxOnCharge_UID { get; set; }
        public string ServiceTaxOnCharge_Desc { get; set; }
        public decimal ServiceTaxOnCharge_ByPer { get; set; }
        public decimal ServiceTaxOnCharge_ByAmount { get; set; }
        public decimal ServiceTaxOnCharge_Amount { get; set; }
        public decimal OtherCharges_UID1 { get; set; }
        public string OtherCharges_Desc1 { get; set; }
        public decimal OtherCharges_ByPer1 { get; set; }
        public decimal OtherCharges_ByAmount1 { get; set; }
        public decimal OtherCharges_Amount1 { get; set; }
        public decimal OtherCharges_UID2 { get; set; }
        public decimal ServiceCharge_ByPer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual BillTrans_SQLite BillTrans_SQLite { get; set; }
    }
}
