//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillProduct_DeliveredStatus_Sqlite
    {
        public decimal UID { get; set; }
        public System.Guid BillPartitionKey { get; set; }
        public decimal BillProductID { get; set; }
        public decimal ProductID { get; set; }
        public bool IsDelivered { get; set; }
        public System.DateTime ReadTime { get; set; }
        public System.Guid DeliveryPartitionKey { get; set; }
    }
}
