//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTrans_SQLite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillTrans_SQLite()
        {
            this.BillTrans_Extn_SQlite = new HashSet<BillTrans_Extn_SQlite>();
            this.BillTrans_TaxLink_SQlite = new HashSet<BillTrans_TaxLink_SQlite>();
            this.BillTransList_SQLite = new HashSet<BillTransList_SQLite>();
            this.BillTransOrderInfo_SQLite = new HashSet<BillTransOrderInfo_SQLite>();
        }
    
        public decimal UID { get; set; }
        public decimal BillID { get; set; }
        public decimal OrderNo { get; set; }
        public string OrderType { get; set; }
        public Nullable<decimal> BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public System.DateTime BillDateTime { get; set; }
        public decimal CaptainID { get; set; }
        public decimal WaiterID { get; set; }
        public decimal BranchID { get; set; }
        public decimal HallID { get; set; }
        public decimal TableID { get; set; }
        public string AddlInfo { get; set; }
        public decimal BillTotal { get; set; }
        public Nullable<decimal> BillNetAmount { get; set; }
        public Nullable<decimal> BillStatusID { get; set; }
        public string TableArea { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string SQLiteFileName { get; set; }
        public Nullable<System.Guid> PartitionKey { get; set; }
        public int CancelledKOT { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string PaymentTypes { get; set; }
        public string PrefixBillNo { get; set; }
        public string PrefixOrderNo { get; set; }
        public string CalcDetails { get; set; }
        public string BillinHTML { get; set; }
        public decimal PaymentGatewayRefID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillTrans_Extn_SQlite> BillTrans_Extn_SQlite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillTrans_TaxLink_SQlite> BillTrans_TaxLink_SQlite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillTransList_SQLite> BillTransList_SQLite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillTransOrderInfo_SQLite> BillTransOrderInfo_SQLite { get; set; }
    }
}
