//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillTrans_TransactionSlNos
    {
        public decimal UID { get; set; }
        public string TableName { get; set; }
        public Nullable<decimal> LastID { get; set; }
        public Nullable<decimal> RestaurantID { get; set; }
    }
}
