//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelledStockListLink
    {
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal Department_UID { get; set; }
        public decimal RefTransList_UID { get; set; }
        public decimal ItemsM_UID { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public System.DateTime RefDocumentDate { get; set; }
        public string EntryType { get; set; }
        public string CancelledType { get; set; }
        public decimal StatusM_UID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string AdditionalInformation { get; set; }
    }
}
