//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashierCollectionInfo
    {
        public decimal UID { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal Cashier_UID { get; set; }
        public decimal CollectionType { get; set; }
        public decimal CollectedAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Remarks { get; set; }
    }
}
