//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashInOutDetail
    {
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public int DocumentNo { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public System.DateTime DocumentTime { get; set; }
        public int DocType { get; set; }
        public decimal Cashier_UID { get; set; }
        public decimal OpeningAmount { get; set; }
        public decimal TotalSales { get; set; }
        public decimal ClosingAmount { get; set; }
        public decimal SettledAmount { get; set; }
        public decimal DifferenceAmount { get; set; }
        public decimal FromBillTrans_UID { get; set; }
        public decimal FromPaymentType_UID { get; set; }
        public decimal ToBillTrans_UID { get; set; }
        public decimal ToPaymentType_UID { get; set; }
        public decimal ShiftUID { get; set; }
        public decimal StatusM_UID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public decimal CreatedBy { get; set; }
        public decimal ApprovedBy { get; set; }
    }
}
