//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeM
    {
        public decimal UId { get; set; }
        public string ChequeBookNo { get; set; }
        public decimal AccountM_UId { get; set; }
        public decimal FromChequeLeafNo { get; set; }
        public decimal ToChequeLeafNo { get; set; }
        public System.DateTime ChequeBookIssuedDate { get; set; }
        public System.DateTime PreparedDate { get; set; }
        public decimal BranchID { get; set; }
    }
}
