//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChequeMList
    {
        public decimal UId { get; set; }
        public decimal ChequeM_UId { get; set; }
        public decimal ChequeLeafNo { get; set; }
        public decimal StatusM_UId { get; set; }
    }
}
