//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CloudOrderDownloadStatu
    {
        public decimal UID { get; set; }
        public decimal BranchUID { get; set; }
        public decimal ChangeSetID { get; set; }
        public string DownloadedFileName { get; set; }
        public int MasterUploadStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public decimal ItemChangeSetID { get; set; }
    }
}
