//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectionTran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollectionTran()
        {
            this.CollectionTransLinks = new HashSet<CollectionTransLink>();
        }
    
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal AccountMGroups_UID { get; set; }
        public int FinYear { get; set; }
        public decimal ShiftM_UID { get; set; }
        public decimal Cashier_UID { get; set; }
        public Nullable<decimal> CollectionAmount { get; set; }
        public string Remarks { get; set; }
        public decimal StatusM_UID { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public int DocumentTypeM_UID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> PaymentType_UID { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal ApprovedUser_UID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectionTransLink> CollectionTransLinks { get; set; }
    }
}
