//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommodityM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommodityM()
        {
            this.CommodityM_AccountM_Mapping = new HashSet<CommodityM_AccountM_Mapping>();
            this.CommodityM_AccountMItems_Mapping = new HashSet<CommodityM_AccountMItems_Mapping>();
            this.CommodityM_Hall_Mapping = new HashSet<CommodityM_Hall_Mapping>();
        }
    
        public decimal CommodityUID { get; set; }
        public string ChapterCode { get; set; }
        public string ChapterDescription { get; set; }
        public string CommodityCode { get; set; }
        public string CommodityDescription { get; set; }
        public string CommodityType { get; set; }
        public decimal RateOfTax { get; set; }
        public string StringAttribute1 { get; set; }
        public string StringAttribute2 { get; set; }
        public Nullable<System.DateTime> DateAttribute1 { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityM_AccountM_Mapping> CommodityM_AccountM_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityM_AccountMItems_Mapping> CommodityM_AccountMItems_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityM_Hall_Mapping> CommodityM_Hall_Mapping { get; set; }
    }
}
