//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponCodeM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CouponCodeM()
        {
            this.CouponCodeM_CustomerMapping = new HashSet<CouponCodeM_CustomerMapping>();
            this.CouponCodeM_PromoMapping = new HashSet<CouponCodeM_PromoMapping>();
        }
    
        public decimal UID { get; set; }
        public string CouponCode { get; set; }
        public int CouponCount { get; set; }
        public int CouponUsed { get; set; }
        public bool IsActive { get; set; }
        public string CouponApproved { get; set; }
        public string CouponType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponCodeM_CustomerMapping> CouponCodeM_CustomerMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CouponCodeM_PromoMapping> CouponCodeM_PromoMapping { get; set; }
    }
}
