//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditBillPaymentDetail
    {
        public decimal UID { get; set; }
        public decimal CreditBillTrans_UID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public System.DateTime PaymentTime { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
    }
}
