//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditBillTran
    {
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public decimal Total { get; set; }
        public decimal NettValue { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal Roundoff { get; set; }
        public decimal Partner_UID { get; set; }
        public decimal Cashier_UID { get; set; }
        public decimal StatusM_UID { get; set; }
    }
}
