//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Criterion
    {
        public decimal UID { get; set; }
        public string ReportName { get; set; }
        public string DisplayName { get; set; }
        public string ValueName { get; set; }
        public int DType { get; set; }
    }
}
