//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_LoyaltyHistory
    {
        public decimal UID { get; set; }
        public decimal Customer_UID { get; set; }
        public decimal BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public decimal SalesValue { get; set; }
        public decimal PointsAcquired { get; set; }
        public decimal PointsRedeem { get; set; }
        public decimal BalancePoints { get; set; }
        public decimal BalanceAmount { get; set; }
        public string CustomerName { get; set; }
    }
}
