//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAccount
    {
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal AccountID { get; set; }
        public decimal Opening { get; set; }
        public decimal Debit { get; set; }
        public decimal Credit { get; set; }
        public decimal Closing { get; set; }
        public System.DateTime ClosedDate { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public decimal Sqlite_UID { get; set; }
    }
}
