//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataUploadLog
    {
        public decimal SlNo { get; set; }
        public decimal Branch { get; set; }
        public decimal ServerRecCount { get; set; }
        public decimal ClientRecCount { get; set; }
    }
}
