//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceInformation
    {
        public decimal UID { get; set; }
        public string AppSerialNo { get; set; }
        public string DeviceSerialNo { get; set; }
        public string DeviceType { get; set; }
        public string DeviceName { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
