//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicePrintConfigurationM
    {
        public decimal UID { get; set; }
        public Nullable<decimal> LoginHall_UID { get; set; }
        public Nullable<decimal> PrintHall_UID { get; set; }
        public string IPAddress { get; set; }
        public string KOTPrinterName { get; set; }
        public string KOTIpAddress { get; set; }
        public Nullable<decimal> Branch_UID { get; set; }
        public string ServiceReqIP { get; set; }
        public string ServiceReqPrinter { get; set; }
        public string TakeAwayPrinterIP { get; set; }
        public string TakeAwayPrinterName { get; set; }
        public string BillPrinterName { get; set; }
        public string DuplicateKOTPrinterIp { get; set; }
        public string DuplicateKOTPrinterName { get; set; }
        public string CashDrawerPrinter { get; set; }
        public string DuplicateTakeAwayPrinterName { get; set; }
        public string TableTransferPrinter { get; set; }
        public string ShelfItemPrinter { get; set; }
        public string IsParcelPrinter { get; set; }
        public string CashReceiptPrinter { get; set; }
        public string PrintCount { get; set; }
        public string TokenMemoPrinter { get; set; }
    }
}
