//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DineGroup_ImageMapping
    {
        public decimal UID { get; set; }
        public decimal DineGroupUID { get; set; }
        public string DineGroupImageName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string DineGroupLanguageName { get; set; }
        public Nullable<decimal> OrderNo { get; set; }
        public string DineGroupLanguagePrintName { get; set; }
    }
}
