//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTypeMBranch
    {
        public int DocumentTypeM_UID { get; set; }
        public decimal Branch_UID { get; set; }
        public string Prefix { get; set; }
        public int UnderDocumentTypeM_UID { get; set; }
        public decimal DefaultStatusM_UID { get; set; }
        public int DocGenType { get; set; }
    }
}
