//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentHistory
    {
        public decimal UID { get; set; }
        public string LongDocumentNo { get; set; }
        public Nullable<decimal> BranchID { get; set; }
        public Nullable<decimal> AccountMGroup_UID { get; set; }
        public Nullable<decimal> DocumentTypeID { get; set; }
        public Nullable<decimal> DataState { get; set; }
        public Nullable<decimal> UserID { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
    }
}
