//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTypeMList
    {
        public int DocumentTypeM_UID { get; set; }
        public decimal Branch_UID { get; set; }
        public int Yr { get; set; }
        public int Mon { get; set; }
        public Nullable<decimal> LastId { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public decimal AccountMGroups_UID { get; set; }
    }
}
