//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emailconfiguration
    {
        public decimal UID { get; set; }
        public bool IsNeeded { get; set; }
        public string FromAddress { get; set; }
        public string Password { get; set; }
        public string HostName { get; set; }
        public string Port { get; set; }
        public string ToAddress { get; set; }
        public int Interval { get; set; }
        public System.DateTime LastMailSentTime { get; set; }
        public System.DateTime TimetoSent { get; set; }
        public bool SendbyTime { get; set; }
        public string SystemMail { get; set; }
        public bool IsSMSNeeded { get; set; }
        public string MobileNumbers { get; set; }
        public string Cc { get; set; }
        public string BCc { get; set; }
    }
}
