//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeList
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Organization { get; set; }
        public string Location { get; set; }
    }
}
