//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeM_WagesDetails
    {
        public decimal UID { get; set; }
        public decimal EmployeeM_UID { get; set; }
        public decimal PayType_UID { get; set; }
        public decimal Pay { get; set; }
        public decimal MinWorkingHour { get; set; }
        public decimal OverTimePay { get; set; }
    }
}
