//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeM()
        {
            this.EmployeeM_BranchMapping = new HashSet<EmployeeM_BranchMapping>();
        }
    
        public decimal UID { get; set; }
        public decimal AccountM_UID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string Sex { get; set; }
        public string FatherName { get; set; }
        public decimal Designation_UID { get; set; }
        public decimal MaritalStatus_UID { get; set; }
        public byte[] Photo { get; set; }
        public string Password { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string City { get; set; }
        public string Pincode { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public decimal Branch_UID { get; set; }
        public bool IsLoginAllowed { get; set; }
        public decimal State_UID { get; set; }
        public string SI_No { get; set; }
        public Nullable<decimal> RegionLanguageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeM_BranchMapping> EmployeeM_BranchMapping { get; set; }
    }
}
