//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExeMaster
    {
        public decimal UID { get; set; }
        public string ExeName { get; set; }
        public string TaskDesc { get; set; }
        public bool SchedulerNeeded { get; set; }
        public int SchedulerAdded { get; set; }
        public string ExeType { get; set; }
    }
}
