//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_Sales
    {
        public decimal UID { get; set; }
        public System.DateTime BillDate { get; set; }
        public string EXP_ShiftCode { get; set; }
        public string EXP_BranchCode { get; set; }
        public string EXP_SaleCode { get; set; }
        public string EXP_ItemCode { get; set; }
        public decimal EXP_ItemQty { get; set; }
        public decimal EXP_Discount { get; set; }
        public System.DateTime UploadDate { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Upload_VBELN { get; set; }
        public bool Upload_Status { get; set; }
        public string Upload_Msg { get; set; }
    }
}
