//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXP_Payment
    {
        public decimal UID { get; set; }
        public System.DateTime CollectionDate { get; set; }
        public string EXP_BranchCode { get; set; }
        public string EXP_SettlementCode { get; set; }
        public decimal EXP_Amount { get; set; }
        public int M_TableCode { get; set; }
        public System.DateTime UploadDate { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Upload_DOCNUMBER { get; set; }
        public bool Upload_Status { get; set; }
        public string Upload_Msg { get; set; }
    }
}
