//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_RegionalFontMapping
    {
        public decimal UID { get; set; }
        public string FormName { get; set; }
        public string ControlName { get; set; }
        public string GeneralFont { get; set; }
        public string RegionalFont { get; set; }
        public int IsActive { get; set; }
    }
}
