//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreeIssueTran
    {
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal AccountM_UID { get; set; }
        public int DocumentTypeM_UID { get; set; }
        public int FinYear { get; set; }
        public decimal BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string LongDocumentNo { get; set; }
        public decimal Table_UID { get; set; }
        public decimal Waiter_UID { get; set; }
        public decimal ShiftM_UID { get; set; }
        public decimal FromTokenNo { get; set; }
        public decimal ToTokenNo { get; set; }
        public decimal Total { get; set; }
        public decimal TaxPercent { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal SurchargePercent { get; set; }
        public decimal SurchargeAmount { get; set; }
        public decimal ParcelCharge { get; set; }
        public decimal ACCharge { get; set; }
        public decimal DeliveryCharges { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public decimal NettValue { get; set; }
        public decimal PaymentTypeM_UID { get; set; }
        public string Reference { get; set; }
        public string Remarks { get; set; }
        public decimal KOTTrans_UID { get; set; }
        public decimal CollectedAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal StatusM_UID { get; set; }
        public string TableSplit { get; set; }
        public Nullable<decimal> Tax_UID { get; set; }
        public decimal Cashier_UID { get; set; }
    }
}
