//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTSplitPercentage
    {
        public decimal UID { get; set; }
        public Nullable<decimal> StateID { get; set; }
        public Nullable<decimal> SGSTPrecentage { get; set; }
        public Nullable<decimal> CGSTPrecentage { get; set; }
        public Nullable<decimal> IGSTPrecentage { get; set; }
    }
}
