//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class HallTimeMappingHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HallTimeMappingHeader()
        {
            this.HallTimeMappingLists = new HashSet<HallTimeMappingList>();
        }
    
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public decimal Hall_UID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HallTimeMappingList> HallTimeMappingLists { get; set; }
    }
}
