//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsCloudServer
    {
        public decimal UID { get; set; }
        public bool IsCloudServer1 { get; set; }
        public bool IsCustomerUpload { get; set; }
        public bool AllowItemCreation { get; set; }
    }
}
