//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTimeMapping
    {
        public decimal UID { get; set; }
        public decimal TimeMaster_UID { get; set; }
        public decimal Items_UID { get; set; }
        public decimal OrderNo { get; set; }
        public Nullable<bool> InUse { get; set; }
        public Nullable<System.DateTime> Modifieddate { get; set; }
    }
}
