//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class KMPOSStockTransList
    {
        public decimal UID { get; set; }
        public decimal StockTransList_UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal AccountMGroups_UID { get; set; }
        public Nullable<decimal> DocumentNumber { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public int DocumentTypeM_UID { get; set; }
        public decimal ItemsM_UID { get; set; }
        public decimal UOM_UID { get; set; }
        public decimal Rec_Qty { get; set; }
        public decimal Iss_Qty { get; set; }
        public decimal BalanceQty { get; set; }
        public decimal StockRate { get; set; }
        public decimal W_Rate { get; set; }
        public bool IsSalesQty { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal Opening_Qty { get; set; }
        public decimal Wastage_Qty { get; set; }
        public decimal ConversionUOM_Qty { get; set; }
        public decimal ConversionUOM_Rate { get; set; }
        public decimal ConversionUOM_UID { get; set; }
        public Nullable<decimal> Receipt_Value { get; set; }
        public Nullable<decimal> Issue_Value { get; set; }
        public Nullable<decimal> Opening_Value { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public decimal SalesValue { get; set; }
    }
}
