//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KOTEntities : DbContext
    {
        public KOTEntities()
            : base("name=KOTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccCashSettlement> AccCashSettlements { get; set; }
        public virtual DbSet<AccountClosing> AccountClosings { get; set; }
        public virtual DbSet<AccountHeadsLevel> AccountHeadsLevels { get; set; }
        public virtual DbSet<AccountM> AccountMs { get; set; }
        public virtual DbSet<AccountM_CardDetails> AccountM_CardDetails { get; set; }
        public virtual DbSet<AccountM_CardDetails_History> AccountM_CardDetails_History { get; set; }
        public virtual DbSet<AccountM_CardDetailsList> AccountM_CardDetailsList { get; set; }
        public virtual DbSet<AccountMConfiguration> AccountMConfigurations { get; set; }
        public virtual DbSet<AccountMCustomerLink> AccountMCustomerLinks { get; set; }
        public virtual DbSet<AccountMGroup> AccountMGroups { get; set; }
        public virtual DbSet<AccountMGroups_Branch> AccountMGroups_Branch { get; set; }
        public virtual DbSet<AccountMItem> AccountMItems { get; set; }
        public virtual DbSet<AccountMItems_CommissionM> AccountMItems_CommissionM { get; set; }
        public virtual DbSet<AccountMItems_ContainerMapping> AccountMItems_ContainerMapping { get; set; }
        public virtual DbSet<AccountMItems_DiscountMapping> AccountMItems_DiscountMapping { get; set; }
        public virtual DbSet<AccountmItems_FoodType> AccountmItems_FoodType { get; set; }
        public virtual DbSet<AccountMItems_ImageMapping> AccountMItems_ImageMapping { get; set; }
        public virtual DbSet<AccountMItems_RelationList> AccountMItems_RelationList { get; set; }
        public virtual DbSet<AccountMItems_ServiceChargeMapping> AccountMItems_ServiceChargeMapping { get; set; }
        public virtual DbSet<AccountMItems_ServiceTaxMapping> AccountMItems_ServiceTaxMapping { get; set; }
        public virtual DbSet<AccountMItems_UsageRatio> AccountMItems_UsageRatio { get; set; }
        public virtual DbSet<AccountMItems_VatMapping> AccountMItems_VatMapping { get; set; }
        public virtual DbSet<AccountMItemsBOM> AccountMItemsBOMs { get; set; }
        public virtual DbSet<AccountMItemsBrand> AccountMItemsBrands { get; set; }
        public virtual DbSet<AccountMItemsFGBOM> AccountMItemsFGBOMs { get; set; }
        public virtual DbSet<AccountMItemsList> AccountMItemsLists { get; set; }
        public virtual DbSet<AccountMItemsMultiUOM> AccountMItemsMultiUOMs { get; set; }
        public virtual DbSet<AccountMItemsPartnersLink> AccountMItemsPartnersLinks { get; set; }
        public virtual DbSet<AccountMItemsSalesUOM> AccountMItemsSalesUOMs { get; set; }
        public virtual DbSet<AccountMPartner> AccountMPartners { get; set; }
        public virtual DbSet<AccountMPartners_CardMaster> AccountMPartners_CardMaster { get; set; }
        public virtual DbSet<AccountMPartners_Extn> AccountMPartners_Extn { get; set; }
        public virtual DbSet<AccountMPartnersAddress> AccountMPartnersAddresses { get; set; }
        public virtual DbSet<AccountMPartnersContact> AccountMPartnersContacts { get; set; }
        public virtual DbSet<AccountMPartnersTD> AccountMPartnersTDS { get; set; }
        public virtual DbSet<AccountMPartnerTerm> AccountMPartnerTerms { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<AccTran> AccTrans { get; set; }
        public virtual DbSet<AccTrans_BillTrans_Link> AccTrans_BillTrans_Link { get; set; }
        public virtual DbSet<AccTrans_BranchAccountTrans_Link> AccTrans_BranchAccountTrans_Link { get; set; }
        public virtual DbSet<AccTrans_PaymentTrans_Link> AccTrans_PaymentTrans_Link { get; set; }
        public virtual DbSet<AccTrans_SqlLiteLink> AccTrans_SqlLiteLink { get; set; }
        public virtual DbSet<AccTrans_StockTrans_Link> AccTrans_StockTrans_Link { get; set; }
        public virtual DbSet<AccTransDocument> AccTransDocuments { get; set; }
        public virtual DbSet<AccTransLink> AccTransLinks { get; set; }
        public virtual DbSet<AccTransList> AccTransLists { get; set; }
        public virtual DbSet<AccTransListBranchList> AccTransListBranchLists { get; set; }
        public virtual DbSet<AccTransListCostCentre> AccTransListCostCentres { get; set; }
        public virtual DbSet<AccTransListMatch> AccTransListMatches { get; set; }
        public virtual DbSet<AreaMaster> AreaMasters { get; set; }
        public virtual DbSet<BarAtGlanceAbstract> BarAtGlanceAbstracts { get; set; }
        public virtual DbSet<BillPrintingQueue> BillPrintingQueues { get; set; }
        public virtual DbSet<BillPrintMemoQueue1> BillPrintMemoQueue1 { get; set; }
        public virtual DbSet<BillProduct_DeliveredStatus_Sqlite> BillProduct_DeliveredStatus_Sqlite { get; set; }
        public virtual DbSet<BillTran> BillTrans { get; set; }
        public virtual DbSet<BillTrans_BranchMapping> BillTrans_BranchMapping { get; set; }
        public virtual DbSet<BillTrans_CalculationSQLite> BillTrans_CalculationSQLite { get; set; }
        public virtual DbSet<BillTrans_EmployeeXferDetails> BillTrans_EmployeeXferDetails { get; set; }
        public virtual DbSet<BillTrans_Extn> BillTrans_Extn { get; set; }
        public virtual DbSet<BillTrans_Extn_SQlite> BillTrans_Extn_SQlite { get; set; }
        public virtual DbSet<BillTrans_FoodPreparation_Status> BillTrans_FoodPreparation_Status { get; set; }
        public virtual DbSet<BillTrans_SQLite> BillTrans_SQLite { get; set; }
        public virtual DbSet<BillTrans_SQLite_Status> BillTrans_SQLite_Status { get; set; }
        public virtual DbSet<BillTrans_SqlLiteLink> BillTrans_SqlLiteLink { get; set; }
        public virtual DbSet<BillTrans_TaxLink> BillTrans_TaxLink { get; set; }
        public virtual DbSet<BillTrans_TaxLink_SQlite> BillTrans_TaxLink_SQlite { get; set; }
        public virtual DbSet<BillTrans_TaxLinkList> BillTrans_TaxLinkList { get; set; }
        public virtual DbSet<BillTrans_TransactionSlNos> BillTrans_TransactionSlNos { get; set; }
        public virtual DbSet<BillTransList> BillTransLists { get; set; }
        public virtual DbSet<BillTransList_AddOnsList> BillTransList_AddOnsList { get; set; }
        public virtual DbSet<BillTransList_AddOnsList_SQLite> BillTransList_AddOnsList_SQLite { get; set; }
        public virtual DbSet<BillTransList_DiscountList> BillTransList_DiscountList { get; set; }
        public virtual DbSet<BillTransList_DiscountList_SQLite> BillTransList_DiscountList_SQLite { get; set; }
        public virtual DbSet<BillTransList_IsDeliveredList> BillTransList_IsDeliveredList { get; set; }
        public virtual DbSet<BillTransList_SQLite> BillTransList_SQLite { get; set; }
        public virtual DbSet<BillTransList_StockTransList_Link> BillTransList_StockTransList_Link { get; set; }
        public virtual DbSet<BillTransList_TransactionSlNos> BillTransList_TransactionSlNos { get; set; }
        public virtual DbSet<BillTransOrderInfo_SQLite> BillTransOrderInfo_SQLite { get; set; }
        public virtual DbSet<BranchAccountTran> BranchAccountTrans { get; set; }
        public virtual DbSet<BranchAccountTrans_BillTrans_Link> BranchAccountTrans_BillTrans_Link { get; set; }
        public virtual DbSet<BranchHallMapping> BranchHallMappings { get; set; }
        public virtual DbSet<BranchLogoMapping> BranchLogoMappings { get; set; }
        public virtual DbSet<BranchwiseHallMapping> BranchwiseHallMappings { get; set; }
        public virtual DbSet<BuyerInfo> BuyerInfoes { get; set; }
        public virtual DbSet<BuyerInfoConfig> BuyerInfoConfigs { get; set; }
        public virtual DbSet<CalendarM> CalendarMs { get; set; }
        public virtual DbSet<CancelledBill> CancelledBills { get; set; }
        public virtual DbSet<CancelledBillTransList> CancelledBillTransLists { get; set; }
        public virtual DbSet<CancelledStockListLink> CancelledStockListLinks { get; set; }
        public virtual DbSet<CancelledTransList> CancelledTransLists { get; set; }
        public virtual DbSet<Captain_TableMapping> Captain_TableMapping { get; set; }
        public virtual DbSet<CashierCollectionInfo> CashierCollectionInfoes { get; set; }
        public virtual DbSet<CashierMapping> CashierMappings { get; set; }
        public virtual DbSet<CashInOutDetail> CashInOutDetails { get; set; }
        public virtual DbSet<CashInOutDetailsDenomination> CashInOutDetailsDenominations { get; set; }
        public virtual DbSet<CategoryAccountMLink> CategoryAccountMLinks { get; set; }
        public virtual DbSet<ChequeM> ChequeMs { get; set; }
        public virtual DbSet<ChequeMList> ChequeMLists { get; set; }
        public virtual DbSet<CloudOrderDownloadStatu> CloudOrderDownloadStatus { get; set; }
        public virtual DbSet<CollectionTran> CollectionTrans { get; set; }
        public virtual DbSet<CollectionTransLink> CollectionTransLinks { get; set; }
        public virtual DbSet<CommissionM> CommissionMs { get; set; }
        public virtual DbSet<CommodityM> CommodityMs { get; set; }
        public virtual DbSet<CommodityM_AccountM_Mapping> CommodityM_AccountM_Mapping { get; set; }
        public virtual DbSet<CommodityM_AccountMItems_Mapping> CommodityM_AccountMItems_Mapping { get; set; }
        public virtual DbSet<CommodityM_Hall_Mapping> CommodityM_Hall_Mapping { get; set; }
        public virtual DbSet<CommodityM_ServiceTaxMaster_Mapping> CommodityM_ServiceTaxMaster_Mapping { get; set; }
        public virtual DbSet<CompanyLogoMapping> CompanyLogoMappings { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<ConfigurationM> ConfigurationMs { get; set; }
        public virtual DbSet<ConfigurationsM> ConfigurationsMs { get; set; }
        public virtual DbSet<ContainerM> ContainerMs { get; set; }
        public virtual DbSet<CouponCodeM> CouponCodeMs { get; set; }
        public virtual DbSet<CouponCodeM_CustomerMapping> CouponCodeM_CustomerMapping { get; set; }
        public virtual DbSet<CouponCodeM_PromoMapping> CouponCodeM_PromoMapping { get; set; }
        public virtual DbSet<CreditBillPayment> CreditBillPayments { get; set; }
        public virtual DbSet<CreditBillPaymentDetail> CreditBillPaymentDetails { get; set; }
        public virtual DbSet<CreditBillTran> CreditBillTrans { get; set; }
        public virtual DbSet<CreditBillTransList> CreditBillTransLists { get; set; }
        public virtual DbSet<Criterion> Criteria { get; set; }
        public virtual DbSet<CurrencyM> CurrencyMs { get; set; }
        public virtual DbSet<CurrencyMList> CurrencyMLists { get; set; }
        public virtual DbSet<Customer_Loyalty> Customer_Loyalty { get; set; }
        public virtual DbSet<Customer_LoyaltyHistory> Customer_LoyaltyHistory { get; set; }
        public virtual DbSet<CustomerFeedBack> CustomerFeedBacks { get; set; }
        public virtual DbSet<CustomerFeedBackList> CustomerFeedBackLists { get; set; }
        public virtual DbSet<CustomerM> CustomerMs { get; set; }
        public virtual DbSet<CustomerServiceRequest> CustomerServiceRequests { get; set; }
        public virtual DbSet<DailyAccount> DailyAccounts { get; set; }
        public virtual DbSet<DailyItemPurchase> DailyItemPurchases { get; set; }
        public virtual DbSet<DailyStockClosing> DailyStockClosings { get; set; }
        public virtual DbSet<DashboardMenu> DashboardMenus { get; set; }
        public virtual DbSet<DataUploadLog> DataUploadLogs { get; set; }
        public virtual DbSet<DeliveryTran> DeliveryTrans { get; set; }
        public virtual DbSet<DeviceInformation> DeviceInformations { get; set; }
        public virtual DbSet<DevicePrintConfigurationM> DevicePrintConfigurationMs { get; set; }
        public virtual DbSet<DineGroup_ImageMapping> DineGroup_ImageMapping { get; set; }
        public virtual DbSet<DineGroup_InstructionMapping> DineGroup_InstructionMapping { get; set; }
        public virtual DbSet<DiscountM> DiscountMs { get; set; }
        public virtual DbSet<DocNoGeneration> DocNoGenerations { get; set; }
        public virtual DbSet<DocumentHistory> DocumentHistories { get; set; }
        public virtual DbSet<DocumentTypeM> DocumentTypeMs { get; set; }
        public virtual DbSet<DocumentTypeMBranch> DocumentTypeMBranches { get; set; }
        public virtual DbSet<DocumentTypeMList> DocumentTypeMLists { get; set; }
        public virtual DbSet<EasyOrderBillPayment> EasyOrderBillPayments { get; set; }
        public virtual DbSet<EasyOrderBill> EasyOrderBills { get; set; }
        public virtual DbSet<EasyOrderBillsResponse> EasyOrderBillsResponses { get; set; }
        public virtual DbSet<EazyStoreHallDetail> EazyStoreHallDetails { get; set; }
        public virtual DbSet<EDI_DC40> EDI_DC40 { get; set; }
        public virtual DbSet<Emailconfiguration> Emailconfigurations { get; set; }
        public virtual DbSet<Employee_LeaveDetails> Employee_LeaveDetails { get; set; }
        public virtual DbSet<Employee_WorkAllocation> Employee_WorkAllocation { get; set; }
        public virtual DbSet<EmployeeList> EmployeeLists { get; set; }
        public virtual DbSet<EmployeeM> EmployeeMs { get; set; }
        public virtual DbSet<EmployeeM_BranchMapping> EmployeeM_BranchMapping { get; set; }
        public virtual DbSet<EmployeeM_WagesDetails> EmployeeM_WagesDetails { get; set; }
        public virtual DbSet<ExceptionalGroupForEmp> ExceptionalGroupForEmps { get; set; }
        public virtual DbSet<ExeMaster> ExeMasters { get; set; }
        public virtual DbSet<ExeScheduler_Mapping> ExeScheduler_Mapping { get; set; }
        public virtual DbSet<EXP_AccountM> EXP_AccountM { get; set; }
        public virtual DbSet<EXP_AccountMItems> EXP_AccountMItems { get; set; }
        public virtual DbSet<EXP_MasterM> EXP_MasterM { get; set; }
        public virtual DbSet<EXP_Payment> EXP_Payment { get; set; }
        public virtual DbSet<EXP_Sales> EXP_Sales { get; set; }
        public virtual DbSet<FacilityMaster> FacilityMasters { get; set; }
        public virtual DbSet<FeedBackAnswerMapping> FeedBackAnswerMappings { get; set; }
        public virtual DbSet<FeedBackAnswer> FeedBackAnswers { get; set; }
        public virtual DbSet<FeedBackAnswersTemplate> FeedBackAnswersTemplates { get; set; }
        public virtual DbSet<FeedBackMaster> FeedBackMasters { get; set; }
        public virtual DbSet<FeedBackMasterTemplate> FeedBackMasterTemplates { get; set; }
        public virtual DbSet<FGIssueStoresMapping> FGIssueStoresMappings { get; set; }
        public virtual DbSet<FinancialYearM> FinancialYearMs { get; set; }
        public virtual DbSet<FoodAvaialabilityTemplateM> FoodAvaialabilityTemplateMs { get; set; }
        public virtual DbSet<FoodAvailability> FoodAvailabilities { get; set; }
        public virtual DbSet<Form_RegionalFontMapping> Form_RegionalFontMapping { get; set; }
        public virtual DbSet<FreeIssueTran> FreeIssueTrans { get; set; }
        public virtual DbSet<FreeIssueTransList> FreeIssueTransLists { get; set; }
        public virtual DbSet<GSTSplitPercentage> GSTSplitPercentages { get; set; }
        public virtual DbSet<GuestM> GuestMs { get; set; }
        public virtual DbSet<GuestMList> GuestMLists { get; set; }
        public virtual DbSet<Hall_DuplicatePrintMapping> Hall_DuplicatePrintMapping { get; set; }
        public virtual DbSet<HallCharge> HallCharges { get; set; }
        public virtual DbSet<HallGroupBillno_List> HallGroupBillno_List { get; set; }
        public virtual DbSet<HallGroupBillnoHeader> HallGroupBillnoHeaders { get; set; }
        public virtual DbSet<HallItemsGroupMapping> HallItemsGroupMappings { get; set; }
        public virtual DbSet<HallTimeMappingHeader> HallTimeMappingHeaders { get; set; }
        public virtual DbSet<HallTimeMappingList> HallTimeMappingLists { get; set; }
        public virtual DbSet<HappyhoursM> HappyhoursMs { get; set; }
        public virtual DbSet<HolidayM> HolidayMs { get; set; }
        public virtual DbSet<IdentificationMaster> IdentificationMasters { get; set; }
        public virtual DbSet<IsCloudServer> IsCloudServers { get; set; }
        public virtual DbSet<Item_PrintMapping> Item_PrintMapping { get; set; }
        public virtual DbSet<ItemBarcode_Settings> ItemBarcode_Settings { get; set; }
        public virtual DbSet<ItemCategoryGroupAccountMapping> ItemCategoryGroupAccountMappings { get; set; }
        public virtual DbSet<ItemCategoryGroupMapping> ItemCategoryGroupMappings { get; set; }
        public virtual DbSet<ItemGroupAccountMLink> ItemGroupAccountMLinks { get; set; }
        public virtual DbSet<ItemGroupTaxMapping> ItemGroupTaxMappings { get; set; }
        public virtual DbSet<ItemGroupVATMapping> ItemGroupVATMappings { get; set; }
        public virtual DbSet<ItemPriceMapping> ItemPriceMappings { get; set; }
        public virtual DbSet<ItemsTemplate> ItemsTemplates { get; set; }
        public virtual DbSet<ItemTimeMapping> ItemTimeMappings { get; set; }
        public virtual DbSet<ItemTimeUpdate> ItemTimeUpdates { get; set; }
        public virtual DbSet<JuiceAvailability> JuiceAvailabilities { get; set; }
        public virtual DbSet<KitchenWisePrintM> KitchenWisePrintMs { get; set; }
        public virtual DbSet<KMPOSStockTransList> KMPOSStockTransLists { get; set; }
        public virtual DbSet<KMRightsM> KMRightsMs { get; set; }
        public virtual DbSet<KMUserright> KMUserrights { get; set; }
        public virtual DbSet<KOTItemSentDetail> KOTItemSentDetails { get; set; }
        public virtual DbSet<KOTMemoQueue> KOTMemoQueues { get; set; }
        public virtual DbSet<KOTMemoQueueLink> KOTMemoQueueLinks { get; set; }
        public virtual DbSet<KOTTableGrouping> KOTTableGroupings { get; set; }
        public virtual DbSet<KOTTouch_ButtonConfig> KOTTouch_ButtonConfig { get; set; }
        public virtual DbSet<KOTTran> KOTTrans { get; set; }
        public virtual DbSet<KOTTrans_EmployeeXferDetails> KOTTrans_EmployeeXferDetails { get; set; }
        public virtual DbSet<KOTTrans_Extn> KOTTrans_Extn { get; set; }
        public virtual DbSet<KotTrans_TaxLink> KotTrans_TaxLink { get; set; }
        public virtual DbSet<KotTrans_TaxLinkList> KotTrans_TaxLinkList { get; set; }
        public virtual DbSet<KOTTransList> KOTTransLists { get; set; }
        public virtual DbSet<KOTTransList_AddOnsList> KOTTransList_AddOnsList { get; set; }
        public virtual DbSet<KOTTransList_DeliveryStatus> KOTTransList_DeliveryStatus { get; set; }
        public virtual DbSet<KOTTransList_DiscountList> KOTTransList_DiscountList { get; set; }
        public virtual DbSet<KOTTransList_Extn> KOTTransList_Extn { get; set; }
        public virtual DbSet<KOTTransListCancellation> KOTTransListCancellations { get; set; }
        public virtual DbSet<KOTTransListPreference> KOTTransListPreferences { get; set; }
        public virtual DbSet<LodgingPaymentType> LodgingPaymentTypes { get; set; }
        public virtual DbSet<LodgingRightsM> LodgingRightsMs { get; set; }
        public virtual DbSet<LoginBranchName> LoginBranchNames { get; set; }
        public virtual DbSet<LoginChecking> LoginCheckings { get; set; }
        public virtual DbSet<LoginDepartmentMapping> LoginDepartmentMappings { get; set; }
        public virtual DbSet<LoginDetail> LoginDetails { get; set; }
        public virtual DbSet<LoginStoresMapping> LoginStoresMappings { get; set; }
        public virtual DbSet<MasterM> MasterMs { get; set; }
        public virtual DbSet<MasterSlNo> MasterSlNos { get; set; }
        public virtual DbSet<MasterTemplate> MasterTemplates { get; set; }
        public virtual DbSet<MerchantDetail> MerchantDetails { get; set; }
        public virtual DbSet<MonthlyTaxPaidChallanDetail> MonthlyTaxPaidChallanDetails { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<MultiTemplateLink> MultiTemplateLinks { get; set; }
        public virtual DbSet<Online_StoresSettings> Online_StoresSettings { get; set; }
        public virtual DbSet<Onlineorder_MachineInfo> Onlineorder_MachineInfo { get; set; }
        public virtual DbSet<OrderTran> OrderTrans { get; set; }
        public virtual DbSet<OrderTrans_MultiTemplateLink> OrderTrans_MultiTemplateLink { get; set; }
        public virtual DbSet<OrderTrans_SqlLiteLink> OrderTrans_SqlLiteLink { get; set; }
        public virtual DbSet<OrderTrans_TemplateMLink> OrderTrans_TemplateMLink { get; set; }
        public virtual DbSet<OrderTransAdvance> OrderTransAdvances { get; set; }
        public virtual DbSet<OrderTransAttachment> OrderTransAttachments { get; set; }
        public virtual DbSet<OrderTransBooking> OrderTransBookings { get; set; }
        public virtual DbSet<OrderTransCharge> OrderTransCharges { get; set; }
        public virtual DbSet<OrderTransHallDetail> OrderTransHallDetails { get; set; }
        public virtual DbSet<OrderTransLink> OrderTransLinks { get; set; }
        public virtual DbSet<OrderTransList> OrderTransLists { get; set; }
        public virtual DbSet<OrderTransListLink> OrderTransListLinks { get; set; }
        public virtual DbSet<OrderTransListProcess> OrderTransListProcesses { get; set; }
        public virtual DbSet<OrderTransListSample> OrderTransListSamples { get; set; }
        public virtual DbSet<OrderTransTerm> OrderTransTerms { get; set; }
        public virtual DbSet<OtherConfiguration> OtherConfigurations { get; set; }
        public virtual DbSet<OtherConfiguration_Extn> OtherConfiguration_Extn { get; set; }
        public virtual DbSet<OtherConfiguration_ExtnHistory> OtherConfiguration_ExtnHistory { get; set; }
        public virtual DbSet<OtherConfigurationHistory> OtherConfigurationHistories { get; set; }
        public virtual DbSet<OtherEmailconfiguration> OtherEmailconfigurations { get; set; }
        public virtual DbSet<OtherSetting> OtherSettings { get; set; }
        public virtual DbSet<OtherSettings_Extn> OtherSettings_Extn { get; set; }
        public virtual DbSet<OtherSettings_ExtnHistory> OtherSettings_ExtnHistory { get; set; }
        public virtual DbSet<OtherSettingshistory> OtherSettingshistories { get; set; }
        public virtual DbSet<OutletDetail> OutletDetails { get; set; }
        public virtual DbSet<PAOCUnderAccountMapping> PAOCUnderAccountMappings { get; set; }
        public virtual DbSet<ParcelChargeConfig> ParcelChargeConfigs { get; set; }
        public virtual DbSet<PartyAccountGroup> PartyAccountGroups { get; set; }
        public virtual DbSet<PaymentGatewayM> PaymentGatewayMs { get; set; }
        public virtual DbSet<PaymentSerialNo> PaymentSerialNos { get; set; }
        public virtual DbSet<PaymentType> PaymentTypes { get; set; }
        public virtual DbSet<PaymentType_History> PaymentType_History { get; set; }
        public virtual DbSet<PaymentTypeM> PaymentTypeMs { get; set; }
        public virtual DbSet<PendingPOConfig> PendingPOConfigs { get; set; }
        public virtual DbSet<PettyCashInfo> PettyCashInfoes { get; set; }
        public virtual DbSet<POSItemBatchStock> POSItemBatchStocks { get; set; }
        public virtual DbSet<POSReplicationLog> POSReplicationLogs { get; set; }
        public virtual DbSet<POSStockTransList> POSStockTransLists { get; set; }
        public virtual DbSet<POSStockTransListLink> POSStockTransListLinks { get; set; }
        public virtual DbSet<Preference_ItemM_Link> Preference_ItemM_Link { get; set; }
        public virtual DbSet<PriceGroupMapping> PriceGroupMappings { get; set; }
        public virtual DbSet<PriceListEntry> PriceListEntries { get; set; }
        public virtual DbSet<PriceListEntryHistory> PriceListEntryHistories { get; set; }
        public virtual DbSet<PriceListM> PriceListMs { get; set; }
        public virtual DbSet<PriceListM_AccountMGroups_Link> PriceListM_AccountMGroups_Link { get; set; }
        public virtual DbSet<PriceListMList> PriceListMLists { get; set; }
        public virtual DbSet<PrinterConfiguration> PrinterConfigurations { get; set; }
        public virtual DbSet<PrinterSetting> PrinterSettings { get; set; }
        public virtual DbSet<PrintM> PrintMs { get; set; }
        public virtual DbSet<Promo_BOGO_Header> Promo_BOGO_Header { get; set; }
        public virtual DbSet<Promo_BOGO_List> Promo_BOGO_List { get; set; }
        public virtual DbSet<Promo_Header> Promo_Header { get; set; }
        public virtual DbSet<Promo_Items> Promo_Items { get; set; }
        public virtual DbSet<Promo_Items_Price> Promo_Items_Price { get; set; }
        public virtual DbSet<Promo_Validity> Promo_Validity { get; set; }
        public virtual DbSet<Promo_Value> Promo_Value { get; set; }
        public virtual DbSet<PromoOfferTypeM> PromoOfferTypeMs { get; set; }
        public virtual DbSet<PromoPriceListHistory> PromoPriceListHistories { get; set; }
        public virtual DbSet<QueueTracking> QueueTrackings { get; set; }
        public virtual DbSet<Reconciliation> Reconciliations { get; set; }
        public virtual DbSet<ReconciliationList> ReconciliationLists { get; set; }
        public virtual DbSet<ReconciliationTypeM> ReconciliationTypeMs { get; set; }
        public virtual DbSet<RemoveOldDataTran> RemoveOldDataTrans { get; set; }
        public virtual DbSet<ReplicationLog> ReplicationLogs { get; set; }
        public virtual DbSet<ReportBill> ReportBills { get; set; }
        public virtual DbSet<ReportBillList> ReportBillLists { get; set; }
        public virtual DbSet<ReportGenerationType> ReportGenerationTypes { get; set; }
        public virtual DbSet<RestaurantTypeTemplate> RestaurantTypeTemplates { get; set; }
        public virtual DbSet<RightsM> RightsMs { get; set; }
        public virtual DbSet<RoomAdditionalCharge> RoomAdditionalCharges { get; set; }
        public virtual DbSet<RoomAllocation_Dine> RoomAllocation_Dine { get; set; }
        public virtual DbSet<RoomAllocationAdvance> RoomAllocationAdvances { get; set; }
        public virtual DbSet<RoomAllocationList> RoomAllocationLists { get; set; }
        public virtual DbSet<RoomAllocationTran> RoomAllocationTrans { get; set; }
        public virtual DbSet<RoomBillAdvance> RoomBillAdvances { get; set; }
        public virtual DbSet<RoomBillTran> RoomBillTrans { get; set; }
        public virtual DbSet<RoomBillTransList> RoomBillTransLists { get; set; }
        public virtual DbSet<RoomMaster_Dine> RoomMaster_Dine { get; set; }
        public virtual DbSet<RoomReservationAdvance> RoomReservationAdvances { get; set; }
        public virtual DbSet<RoomReservationList> RoomReservationLists { get; set; }
        public virtual DbSet<RoomReservationTran> RoomReservationTrans { get; set; }
        public virtual DbSet<RoomsM> RoomsMs { get; set; }
        public virtual DbSet<RoomsMFacilityLink> RoomsMFacilityLinks { get; set; }
        public virtual DbSet<RoomTariffMapping> RoomTariffMappings { get; set; }
        public virtual DbSet<SAP_E1KOMG> SAP_E1KOMG { get; set; }
        public virtual DbSet<SAP_E1KONH> SAP_E1KONH { get; set; }
        public virtual DbSet<SAP_E1KONP> SAP_E1KONP { get; set; }
        public virtual DbSet<SAP_E1WPA01> SAP_E1WPA01 { get; set; }
        public virtual DbSet<SAP_E1WPA02> SAP_E1WPA02 { get; set; }
        public virtual DbSet<SAP_E1WPA03> SAP_E1WPA03 { get; set; }
        public virtual DbSet<SAP_E1WPW01> SAP_E1WPW01 { get; set; }
        public virtual DbSet<SAP_E1WPW02> SAP_E1WPW02 { get; set; }
        public virtual DbSet<SAP_E1WXX01> SAP_E1WXX01 { get; set; }
        public virtual DbSet<SAP_EDI_DC40> SAP_EDI_DC40 { get; set; }
        public virtual DbSet<SAP_SettingsM> SAP_SettingsM { get; set; }
        public virtual DbSet<SAPAdvancePayment> SAPAdvancePayments { get; set; }
        public virtual DbSet<SAPBranchSubgroupMapping> SAPBranchSubgroupMappings { get; set; }
        public virtual DbSet<SAPItemMapping> SAPItemMappings { get; set; }
        public virtual DbSet<SAPItemSubGroupDineGroupMapping> SAPItemSubGroupDineGroupMappings { get; set; }
        public virtual DbSet<ServerConfig> ServerConfigs { get; set; }
        public virtual DbSet<ServiceBillList> ServiceBillLists { get; set; }
        public virtual DbSet<ServiceBillTran> ServiceBillTrans { get; set; }
        public virtual DbSet<ServiceOrderPayment> ServiceOrderPayments { get; set; }
        public virtual DbSet<ServiceOrderPrintingOption> ServiceOrderPrintingOptions { get; set; }
        public virtual DbSet<ServiceOrderPrintingOptionHistory> ServiceOrderPrintingOptionHistories { get; set; }
        public virtual DbSet<ServiceOrderPrintingQueue> ServiceOrderPrintingQueues { get; set; }
        public virtual DbSet<ServiceOrderTran> ServiceOrderTrans { get; set; }
        public virtual DbSet<ServiceOrderTrans_TaxLink> ServiceOrderTrans_TaxLink { get; set; }
        public virtual DbSet<ServiceOrderTrans_TaxLinkList> ServiceOrderTrans_TaxLinkList { get; set; }
        public virtual DbSet<ServiceOrderTransList> ServiceOrderTransLists { get; set; }
        public virtual DbSet<ServiceRequestM> ServiceRequestMs { get; set; }
        public virtual DbSet<ServiceTaxMaster> ServiceTaxMasters { get; set; }
        public virtual DbSet<ServiceTaxMaster_List> ServiceTaxMaster_List { get; set; }
        public virtual DbSet<SettingsM> SettingsMs { get; set; }
        public virtual DbSet<SettlementDetail> SettlementDetails { get; set; }
        public virtual DbSet<SettlementInfo> SettlementInfoes { get; set; }
        public virtual DbSet<SettlementLog> SettlementLogs { get; set; }
        public virtual DbSet<Shift_Waiter_TableLink> Shift_Waiter_TableLink { get; set; }
        public virtual DbSet<ShiftM> ShiftMs { get; set; }
        public virtual DbSet<ShiftM_Current> ShiftM_Current { get; set; }
        public virtual DbSet<ShiftMConfiguration> ShiftMConfigurations { get; set; }
        public virtual DbSet<ShiftMConfigurationHistory> ShiftMConfigurationHistories { get; set; }
        public virtual DbSet<ShiftTemplate> ShiftTemplates { get; set; }
        public virtual DbSet<SMSMessageList> SMSMessageLists { get; set; }
        public virtual DbSet<SpecialItemtimeMapping> SpecialItemtimeMappings { get; set; }
        public virtual DbSet<SpecialTimeMaster> SpecialTimeMasters { get; set; }
        public virtual DbSet<SqlpatchUpdatestatu> SqlpatchUpdatestatus { get; set; }
        public virtual DbSet<SQLUpdate> SQLUpdates { get; set; }
        public virtual DbSet<Sqlupdatestatu> Sqlupdatestatus { get; set; }
        public virtual DbSet<StockAdjustment> StockAdjustments { get; set; }
        public virtual DbSet<StockCheckTran> StockCheckTrans { get; set; }
        public virtual DbSet<StockCheckTransList> StockCheckTransLists { get; set; }
        public virtual DbSet<StockClosing> StockClosings { get; set; }
        public virtual DbSet<StockReceiptIssueMatch> StockReceiptIssueMatches { get; set; }
        public virtual DbSet<StockTran> StockTrans { get; set; }
        public virtual DbSet<StockTrans_BillTransLink> StockTrans_BillTransLink { get; set; }
        public virtual DbSet<StockTrans_OrderTransList_Link> StockTrans_OrderTransList_Link { get; set; }
        public virtual DbSet<StockTrans_SqlLiteLink> StockTrans_SqlLiteLink { get; set; }
        public virtual DbSet<StockTransAdvance> StockTransAdvances { get; set; }
        public virtual DbSet<StockTransAttachment> StockTransAttachments { get; set; }
        public virtual DbSet<StockTransCharge> StockTransCharges { get; set; }
        public virtual DbSet<StockTransContainer> StockTransContainers { get; set; }
        public virtual DbSet<StockTransForm> StockTransForms { get; set; }
        public virtual DbSet<StockTransHallDetail> StockTransHallDetails { get; set; }
        public virtual DbSet<StockTransLink> StockTransLinks { get; set; }
        public virtual DbSet<StockTransList> StockTransLists { get; set; }
        public virtual DbSet<StockTransList_MaterialIssueDetails> StockTransList_MaterialIssueDetails { get; set; }
        public virtual DbSet<StockTransList_OrderTransList_Link> StockTransList_OrderTransList_Link { get; set; }
        public virtual DbSet<StockTransListBatch> StockTransListBatches { get; set; }
        public virtual DbSet<StockTransListContainer> StockTransListContainers { get; set; }
        public virtual DbSet<StockTransListContainerOld> StockTransListContainerOlds { get; set; }
        public virtual DbSet<StockTransListHistory> StockTransListHistories { get; set; }
        public virtual DbSet<StockTransListLink> StockTransListLinks { get; set; }
        public virtual DbSet<StockTransListProcess> StockTransListProcesses { get; set; }
        public virtual DbSet<StockTransListRejection> StockTransListRejections { get; set; }
        public virtual DbSet<StockTransOrderTransLink> StockTransOrderTransLinks { get; set; }
        public virtual DbSet<StockTransReceivedItem> StockTransReceivedItems { get; set; }
        public virtual DbSet<StockTransReceivedItemsProcess> StockTransReceivedItemsProcesses { get; set; }
        public virtual DbSet<StockTransTerm> StockTransTerms { get; set; }
        public virtual DbSet<StockValuationList> StockValuationLists { get; set; }
        public virtual DbSet<StockValuationType> StockValuationTypes { get; set; }
        public virtual DbSet<SubGroup_ImageMapping> SubGroup_ImageMapping { get; set; }
        public virtual DbSet<SubGroupIsAddon> SubGroupIsAddons { get; set; }
        public virtual DbSet<SurchargeM> SurchargeMs { get; set; }
        public virtual DbSet<SyncAccountHeadsLevel> SyncAccountHeadsLevels { get; set; }
        public virtual DbSet<SyncAccountM> SyncAccountMs { get; set; }
        public virtual DbSet<SyncAccountMGroup> SyncAccountMGroups { get; set; }
        public virtual DbSet<SyncAccountMItem> SyncAccountMItems { get; set; }
        public virtual DbSet<SyncAccountMitems_Imagemapping> SyncAccountMitems_Imagemapping { get; set; }
        public virtual DbSet<SyncAccountMItems_VatMapping> SyncAccountMItems_VatMapping { get; set; }
        public virtual DbSet<SyncAccountMItemsBOM> SyncAccountMItemsBOMs { get; set; }
        public virtual DbSet<SyncAccountMItemsMultiUOM> SyncAccountMItemsMultiUOMs { get; set; }
        public virtual DbSet<SyncAccountMItemsPartnersLink> SyncAccountMItemsPartnersLinks { get; set; }
        public virtual DbSet<SyncAccountMItemsSalesUOM> SyncAccountMItemsSalesUOMs { get; set; }
        public virtual DbSet<SyncAccountMPartner> SyncAccountMPartners { get; set; }
        public virtual DbSet<SyncAccountType> SyncAccountTypes { get; set; }
        public virtual DbSet<SyncBillTran> SyncBillTrans { get; set; }
        public virtual DbSet<SyncBillTrans_Extn> SyncBillTrans_Extn { get; set; }
        public virtual DbSet<SyncBillTrans_TaxLink> SyncBillTrans_TaxLink { get; set; }
        public virtual DbSet<SyncBillTrans_TaxLinkList> SyncBillTrans_TaxLinkList { get; set; }
        public virtual DbSet<SyncBillTransList> SyncBillTransLists { get; set; }
        public virtual DbSet<SyncBillTransList_DiscountList> SyncBillTransList_DiscountList { get; set; }
        public virtual DbSet<SyncBranchHallMapping> SyncBranchHallMappings { get; set; }
        public virtual DbSet<SyncCAccountM> SyncCAccountMs { get; set; }
        public virtual DbSet<SyncCAccountMGroup> SyncCAccountMGroups { get; set; }
        public virtual DbSet<SyncCAccountMPartner> SyncCAccountMPartners { get; set; }
        public virtual DbSet<SyncCancelledBill> SyncCancelledBills { get; set; }
        public virtual DbSet<SyncCancelledBillTransList> SyncCancelledBillTransLists { get; set; }
        public virtual DbSet<SyncCancelledTransList> SyncCancelledTransLists { get; set; }
        public virtual DbSet<SyncCollectionTran> SyncCollectionTrans { get; set; }
        public virtual DbSet<SyncCollectionTransLink> SyncCollectionTransLinks { get; set; }
        public virtual DbSet<SyncConfig_SQLite> SyncConfig_SQLite { get; set; }
        public virtual DbSet<SyncCustomerFeedBack> SyncCustomerFeedBacks { get; set; }
        public virtual DbSet<SyncCustomerFeedBackList> SyncCustomerFeedBackLists { get; set; }
        public virtual DbSet<SyncCustomerM> SyncCustomerMs { get; set; }
        public virtual DbSet<SyncDineGroup_ImageMapping> SyncDineGroup_ImageMapping { get; set; }
        public virtual DbSet<SyncDocumentTypeM> SyncDocumentTypeMs { get; set; }
        public virtual DbSet<SyncDocumentTypeMBranch> SyncDocumentTypeMBranches { get; set; }
        public virtual DbSet<SyncEmployeeM> SyncEmployeeMs { get; set; }
        public virtual DbSet<SyncFeedBackMaster> SyncFeedBackMasters { get; set; }
        public virtual DbSet<SyncFinancialYearM> SyncFinancialYearMs { get; set; }
        public virtual DbSet<SyncHallTimeMapping_SQLite> SyncHallTimeMapping_SQLite { get; set; }
        public virtual DbSet<SyncHolidayM> SyncHolidayMs { get; set; }
        public virtual DbSet<SyncKMPOSStockTransList> SyncKMPOSStockTransLists { get; set; }
        public virtual DbSet<SyncKOTTableGrouping> SyncKOTTableGroupings { get; set; }
        public virtual DbSet<SyncKotTran> SyncKotTrans { get; set; }
        public virtual DbSet<SyncKotTrans_Extn> SyncKotTrans_Extn { get; set; }
        public virtual DbSet<SyncKotTrans_TaxLink> SyncKotTrans_TaxLink { get; set; }
        public virtual DbSet<SyncKotTrans_TaxLinkList> SyncKotTrans_TaxLinkList { get; set; }
        public virtual DbSet<SyncKotTransList> SyncKotTransLists { get; set; }
        public virtual DbSet<SyncKOTTransList_DiscountList> SyncKOTTransList_DiscountList { get; set; }
        public virtual DbSet<SyncKotTransList_Extn> SyncKotTransList_Extn { get; set; }
        public virtual DbSet<SyncMasterM> SyncMasterMs { get; set; }
        public virtual DbSet<SyncMonth> SyncMonths { get; set; }
        public virtual DbSet<SyncPartner_SQLite> SyncPartner_SQLite { get; set; }
        public virtual DbSet<SyncPaymentType> SyncPaymentTypes { get; set; }
        public virtual DbSet<SyncPOSStockTransList> SyncPOSStockTransLists { get; set; }
        public virtual DbSet<SyncPriceListEntry> SyncPriceListEntries { get; set; }
        public virtual DbSet<SyncPrinterSetting> SyncPrinterSettings { get; set; }
        public virtual DbSet<SyncProduct_SQLite> SyncProduct_SQLite { get; set; }
        public virtual DbSet<SyncRightsM> SyncRightsMs { get; set; }
        public virtual DbSet<SyncServiceTaxMaster> SyncServiceTaxMasters { get; set; }
        public virtual DbSet<SyncShiftM> SyncShiftMs { get; set; }
        public virtual DbSet<SyncShiftMConfiguration> SyncShiftMConfigurations { get; set; }
        public virtual DbSet<SyncSpecialItemtimeMapping> SyncSpecialItemtimeMappings { get; set; }
        public virtual DbSet<SyncSpecialTimeMaster> SyncSpecialTimeMasters { get; set; }
        public virtual DbSet<SyncSyncProduct_SQLite> SyncSyncProduct_SQLite { get; set; }
        public virtual DbSet<SyncTableList> SyncTableLists { get; set; }
        public virtual DbSet<SyncTableM> SyncTableMs { get; set; }
        public virtual DbSet<SyncTableReservationTran> SyncTableReservationTrans { get; set; }
        public virtual DbSet<SyncUserRight> SyncUserRights { get; set; }
        public virtual DbSet<SyncVATConfiguration> SyncVATConfigurations { get; set; }
        public virtual DbSet<TableAllocation> TableAllocations { get; set; }
        public virtual DbSet<TableListM> TableListMs { get; set; }
        public virtual DbSet<TableM> TableMs { get; set; }
        public virtual DbSet<TableM_Clean> TableM_Clean { get; set; }
        public virtual DbSet<TableReservationTran> TableReservationTrans { get; set; }
        public virtual DbSet<TableTransferMemoQueue> TableTransferMemoQueues { get; set; }
        public virtual DbSet<TakeAwayCustomerInfo> TakeAwayCustomerInfoes { get; set; }
        public virtual DbSet<TakeAwayMemoQueue> TakeAwayMemoQueues { get; set; }
        public virtual DbSet<TakeAwayMemoQueue1> TakeAwayMemoQueue1 { get; set; }
        public virtual DbSet<TaxMaster> TaxMasters { get; set; }
        public virtual DbSet<TaxTypeMaster> TaxTypeMasters { get; set; }
        public virtual DbSet<TBTran> TBTrans { get; set; }
        public virtual DbSet<TDSMasterM> TDSMasterMs { get; set; }
        public virtual DbSet<TemplateM> TemplateMs { get; set; }
        public virtual DbSet<TemplateMList> TemplateMLists { get; set; }
        public virtual DbSet<Timemaster> Timemasters { get; set; }
        public virtual DbSet<TimeZone> TimeZones { get; set; }
        public virtual DbSet<TokenMemoQueue> TokenMemoQueues { get; set; }
        public virtual DbSet<TokenMemoQueueLink> TokenMemoQueueLinks { get; set; }
        public virtual DbSet<TokenNoGeneration> TokenNoGenerations { get; set; }
        public virtual DbSet<TransactionSlNo> TransactionSlNos { get; set; }
        public virtual DbSet<UploadDataM> UploadDataMs { get; set; }
        public virtual DbSet<UploadEmployeeM> UploadEmployeeMs { get; set; }
        public virtual DbSet<UserHallMapping> UserHallMappings { get; set; }
        public virtual DbSet<UserRight> UserRights { get; set; }
        public virtual DbSet<VATConfiguration> VATConfigurations { get; set; }
        public virtual DbSet<VatConfiguration_List> VatConfiguration_List { get; set; }
        public virtual DbSet<Waiter_Dept_MappingOption> Waiter_Dept_MappingOption { get; set; }
        public virtual DbSet<WrokFlowM> WrokFlowMs { get; set; }
        public virtual DbSet<ZReport_Config> ZReport_Config { get; set; }
        public virtual DbSet<ZReportInfo> ZReportInfoes { get; set; }
        public virtual DbSet<ZReportInfo_AcccTrans_Link> ZReportInfo_AcccTrans_Link { get; set; }
        public virtual DbSet<ZReportMailHistory> ZReportMailHistories { get; set; }
        public virtual DbSet<BillMemoQueue_LocalMachine> BillMemoQueue_LocalMachine { get; set; }
        public virtual DbSet<CurrencyMHistory> CurrencyMHistories { get; set; }
        public virtual DbSet<IsAdmin> IsAdmins { get; set; }
        public virtual DbSet<ItemTemp> ItemTemps { get; set; }
        public virtual DbSet<KitchenModuleConfig> KitchenModuleConfigs { get; set; }
        public virtual DbSet<KOTMemoQueue_LocalMachine> KOTMemoQueue_LocalMachine { get; set; }
        public virtual DbSet<TakeAwayMemoQueue_LocalMachine> TakeAwayMemoQueue_LocalMachine { get; set; }
        public virtual DbSet<TakeAwayMemoQueue_SQLite> TakeAwayMemoQueue_SQLite { get; set; }
        public virtual DbSet<ED_GetServiceOrderAdvanceInfo> ED_GetServiceOrderAdvanceInfo { get; set; }
        public virtual DbSet<HSNItem> HSNItems { get; set; }
        public virtual DbSet<V_FormIssuedDetails> V_FormIssuedDetails { get; set; }
        public virtual DbSet<V_ItemCosting> V_ItemCosting { get; set; }
        public virtual DbSet<vBilllingData> vBilllingDatas { get; set; }
        public virtual DbSet<vBilllingTableData> vBilllingTableDatas { get; set; }
        public virtual DbSet<vBilllingWaiterData> vBilllingWaiterDatas { get; set; }
        public virtual DbSet<VM_AccountHeads> VM_AccountHeads { get; set; }
        public virtual DbSet<VM_AdditionalCharges> VM_AdditionalCharges { get; set; }
        public virtual DbSet<VM_Container> VM_Container { get; set; }
        public virtual DbSet<VM_Customers> VM_Customers { get; set; }
        public virtual DbSet<Vm_CustomersDetails> Vm_CustomersDetails { get; set; }
        public virtual DbSet<VM_Department> VM_Department { get; set; }
        public virtual DbSet<VM_GetFoodItems> VM_GetFoodItems { get; set; }
        public virtual DbSet<VM_GetFuelItems> VM_GetFuelItems { get; set; }
        public virtual DbSet<VM_GetItems> VM_GetItems { get; set; }
        public virtual DbSet<VM_ItemBrand> VM_ItemBrand { get; set; }
        public virtual DbSet<VM_ItemCategory> VM_ItemCategory { get; set; }
        public virtual DbSet<VM_ItemGroups> VM_ItemGroups { get; set; }
        public virtual DbSet<VM_ItemsFood> VM_ItemsFood { get; set; }
        public virtual DbSet<VM_ItemsRawMaterials> VM_ItemsRawMaterials { get; set; }
        public virtual DbSet<VM_ItemsRawMaterialsItems> VM_ItemsRawMaterialsItems { get; set; }
        public virtual DbSet<VM_ItemSubGroups> VM_ItemSubGroups { get; set; }
        public virtual DbSet<VM_PAOItemsFood> VM_PAOItemsFood { get; set; }
        public virtual DbSet<VM_RejectionReasons> VM_RejectionReasons { get; set; }
        public virtual DbSet<VM_SingleDepartment> VM_SingleDepartment { get; set; }
        public virtual DbSet<VM_SingleStores> VM_SingleStores { get; set; }
        public virtual DbSet<VM_Status> VM_Status { get; set; }
        public virtual DbSet<VM_StoreDetails> VM_StoreDetails { get; set; }
        public virtual DbSet<VM_Stores> VM_Stores { get; set; }
        public virtual DbSet<VM_SubStore> VM_SubStore { get; set; }
        public virtual DbSet<VM_SubStores> VM_SubStores { get; set; }
        public virtual DbSet<VM_Terms> VM_Terms { get; set; }
        public virtual DbSet<VM_Transport> VM_Transport { get; set; }
        public virtual DbSet<VM_UOM> VM_UOM { get; set; }
        public virtual DbSet<VM_Vendors> VM_Vendors { get; set; }
        public virtual DbSet<VM_VendorsDetail> VM_VendorsDetail { get; set; }
        public virtual DbSet<VM_VendorsDetails> VM_VendorsDetails { get; set; }
        public virtual DbSet<VT_BillAccounting> VT_BillAccounting { get; set; }
        public virtual DbSet<VT_GoodsReceipt> VT_GoodsReceipt { get; set; }
        public virtual DbSet<VT_GoodsReceiptInspection> VT_GoodsReceiptInspection { get; set; }
        public virtual DbSet<VT_GoodsReceiptInspectionOpen> VT_GoodsReceiptInspectionOpen { get; set; }
        public virtual DbSet<VT_GoodsReceiptOpen> VT_GoodsReceiptOpen { get; set; }
        public virtual DbSet<VT_MaterialIndent> VT_MaterialIndent { get; set; }
        public virtual DbSet<VT_MaterialIndentDraft> VT_MaterialIndentDraft { get; set; }
        public virtual DbSet<VT_MaterialIndentPending> VT_MaterialIndentPending { get; set; }
        public virtual DbSet<VT_MaterialRequest> VT_MaterialRequest { get; set; }
        public virtual DbSet<VT_MaterialRequestDraft> VT_MaterialRequestDraft { get; set; }
        public virtual DbSet<VT_MaterialRequestPending> VT_MaterialRequestPending { get; set; }
        public virtual DbSet<VT_PurchaseOrder> VT_PurchaseOrder { get; set; }
        public virtual DbSet<VT_PurchaseOrderDraft> VT_PurchaseOrderDraft { get; set; }
        public virtual DbSet<VT_PurchaseOrderOpen> VT_PurchaseOrderOpen { get; set; }
        public virtual DbSet<Vw_BillPendingDelivery> Vw_BillPendingDelivery { get; set; }
        public virtual DbSet<Vw_BillPendingDelivery_Windows> Vw_BillPendingDelivery_Windows { get; set; }
        public virtual DbSet<Vw_BranchMaster> Vw_BranchMaster { get; set; }
        public virtual DbSet<Vw_DocumentBillType> Vw_DocumentBillType { get; set; }
        public virtual DbSet<Vw_DocumentBillType_Advance> Vw_DocumentBillType_Advance { get; set; }
        public virtual DbSet<Vw_GetAllBillType> Vw_GetAllBillType { get; set; }
        public virtual DbSet<VW_GetDevicePrintConfiguration> VW_GetDevicePrintConfiguration { get; set; }
        public virtual DbSet<VW_GetDocumentType> VW_GetDocumentType { get; set; }
        public virtual DbSet<VW_GetEmployee> VW_GetEmployee { get; set; }
        public virtual DbSet<VW_GetLastBillDetails> VW_GetLastBillDetails { get; set; }
        public virtual DbSet<VW_GetLastOrderDetails> VW_GetLastOrderDetails { get; set; }
        public virtual DbSet<VW_GetLastOrderDetails_Reprint> VW_GetLastOrderDetails_Reprint { get; set; }
        public virtual DbSet<VW_GetPayMentDetails> VW_GetPayMentDetails { get; set; }
        public virtual DbSet<VW_GetTransAvailTables> VW_GetTransAvailTables { get; set; }
        public virtual DbSet<VW_GetVatDetails> VW_GetVatDetails { get; set; }
        public virtual DbSet<Vw_KOTPendingDelivery> Vw_KOTPendingDelivery { get; set; }
        public virtual DbSet<Vw_KOTPendingDelivery_Windows> Vw_KOTPendingDelivery_Windows { get; set; }
        public virtual DbSet<Vw_MISBilllingData> Vw_MISBilllingData { get; set; }
        public virtual DbSet<Vw_MISBilllingData_BillNo> Vw_MISBilllingData_BillNo { get; set; }
        public virtual DbSet<Vw_MISBilllingData_BillNumber> Vw_MISBilllingData_BillNumber { get; set; }
        public virtual DbSet<Vw_MISBilllingData_CancelledBillNumber> Vw_MISBilllingData_CancelledBillNumber { get; set; }
        public virtual DbSet<Vw_MISBilllingData_ServiceBillNo> Vw_MISBilllingData_ServiceBillNo { get; set; }
        public virtual DbSet<Vw_MISBilllingData_TaxBillNo> Vw_MISBilllingData_TaxBillNo { get; set; }
        public virtual DbSet<Vw_MISBilllingData_TaxServiceBillNo> Vw_MISBilllingData_TaxServiceBillNo { get; set; }
        public virtual DbSet<Vw_MISHomeDelivery_BillNumber> Vw_MISHomeDelivery_BillNumber { get; set; }
        public virtual DbSet<Vw_MISPartyOrderData_BillNumber> Vw_MISPartyOrderData_BillNumber { get; set; }
        public virtual DbSet<Vw_MISSalesData_ByItem> Vw_MISSalesData_ByItem { get; set; }
        public virtual DbSet<Vw_MISSalesData_ByServiceItem> Vw_MISSalesData_ByServiceItem { get; set; }
        public virtual DbSet<Vw_MISServiceChargeData_ByBillNo> Vw_MISServiceChargeData_ByBillNo { get; set; }
        public virtual DbSet<Vw_MISServiceChargeData_ByServiceBillNo> Vw_MISServiceChargeData_ByServiceBillNo { get; set; }
        public virtual DbSet<VwAccountGroupLevel> VwAccountGroupLevels { get; set; }
        public virtual DbSet<VwAccTransDetail> VwAccTransDetails { get; set; }
        public virtual DbSet<vwMasters_Documents> vwMasters_Documents { get; set; }
        public virtual DbSet<vwMasters_Transactions> vwMasters_Transactions { get; set; }
        public virtual DbSet<vwMasters_TransactionsDocuments> vwMasters_TransactionsDocuments { get; set; }
        public virtual DbSet<VwRawMaterialItemCategory> VwRawMaterialItemCategories { get; set; }
        public virtual DbSet<VwRawMaterialItemGroup> VwRawMaterialItemGroups { get; set; }
        public virtual DbSet<vwBillDet> vwBillDets { get; set; }
        public virtual DbSet<vwBillMst> vwBillMsts { get; set; }
    
        [DbFunction("KOTEntities", "ED_GetComboList")]
        public virtual IQueryable<ED_GetComboList_Result> ED_GetComboList(Nullable<decimal> itemsM_UID, Nullable<decimal> qty)
        {
            var itemsM_UIDParameter = itemsM_UID.HasValue ?
                new ObjectParameter("ItemsM_UID", itemsM_UID) :
                new ObjectParameter("ItemsM_UID", typeof(decimal));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("Qty", qty) :
                new ObjectParameter("Qty", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ED_GetComboList_Result>("[KOTEntities].[ED_GetComboList](@ItemsM_UID, @Qty)", itemsM_UIDParameter, qtyParameter);
        }
    
        [DbFunction("KOTEntities", "ED_GetContainerPriceby_ItemUID")]
        public virtual IQueryable<ED_GetContainerPriceby_ItemUID_Result> ED_GetContainerPriceby_ItemUID(Nullable<decimal> itemUID)
        {
            var itemUIDParameter = itemUID.HasValue ?
                new ObjectParameter("ItemUID", itemUID) :
                new ObjectParameter("ItemUID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ED_GetContainerPriceby_ItemUID_Result>("[KOTEntities].[ED_GetContainerPriceby_ItemUID](@ItemUID)", itemUIDParameter);
        }
    
        [DbFunction("KOTEntities", "ED_GetContainerPriceby_KOTID")]
        public virtual IQueryable<ED_GetContainerPriceby_KOTID_Result> ED_GetContainerPriceby_KOTID(Nullable<decimal> kOTTrans_UID)
        {
            var kOTTrans_UIDParameter = kOTTrans_UID.HasValue ?
                new ObjectParameter("KOTTrans_UID", kOTTrans_UID) :
                new ObjectParameter("KOTTrans_UID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ED_GetContainerPriceby_KOTID_Result>("[KOTEntities].[ED_GetContainerPriceby_KOTID](@KOTTrans_UID)", kOTTrans_UIDParameter);
        }
    
        [DbFunction("KOTEntities", "ED_GetFGItemList")]
        public virtual IQueryable<ED_GetFGItemList_Result> ED_GetFGItemList(Nullable<decimal> itemsM_UID, Nullable<decimal> qty, Nullable<decimal> uom_UID)
        {
            var itemsM_UIDParameter = itemsM_UID.HasValue ?
                new ObjectParameter("ItemsM_UID", itemsM_UID) :
                new ObjectParameter("ItemsM_UID", typeof(decimal));
    
            var qtyParameter = qty.HasValue ?
                new ObjectParameter("Qty", qty) :
                new ObjectParameter("Qty", typeof(decimal));
    
            var uom_UIDParameter = uom_UID.HasValue ?
                new ObjectParameter("Uom_UID", uom_UID) :
                new ObjectParameter("Uom_UID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ED_GetFGItemList_Result>("[KOTEntities].[ED_GetFGItemList](@ItemsM_UID, @Qty, @Uom_UID)", itemsM_UIDParameter, qtyParameter, uom_UIDParameter);
        }
    
        [DbFunction("KOTEntities", "ED_GetGroupedTables")]
        public virtual IQueryable<ED_GetGroupedTables_Result> ED_GetGroupedTables(Nullable<decimal> kOTTrans_UID)
        {
            var kOTTrans_UIDParameter = kOTTrans_UID.HasValue ?
                new ObjectParameter("KOTTrans_UID", kOTTrans_UID) :
                new ObjectParameter("KOTTrans_UID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ED_GetGroupedTables_Result>("[KOTEntities].[ED_GetGroupedTables](@KOTTrans_UID)", kOTTrans_UIDParameter);
        }
    
        [DbFunction("KOTEntities", "ED_GetHappyHourDiscount")]
        public virtual IQueryable<ED_GetHappyHourDiscount_Result> ED_GetHappyHourDiscount(Nullable<decimal> totalValue)
        {
            var totalValueParameter = totalValue.HasValue ?
                new ObjectParameter("TotalValue", totalValue) :
                new ObjectParameter("TotalValue", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ED_GetHappyHourDiscount_Result>("[KOTEntities].[ED_GetHappyHourDiscount](@TotalValue)", totalValueParameter);
        }
    
        [DbFunction("KOTEntities", "ED_GetSOVatInfo")]
        public virtual IQueryable<ED_GetSOVatInfo_Result> ED_GetSOVatInfo(Nullable<decimal> serviceOrderTrans_UID)
        {
            var serviceOrderTrans_UIDParameter = serviceOrderTrans_UID.HasValue ?
                new ObjectParameter("ServiceOrderTrans_UID", serviceOrderTrans_UID) :
                new ObjectParameter("ServiceOrderTrans_UID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ED_GetSOVatInfo_Result>("[KOTEntities].[ED_GetSOVatInfo](@ServiceOrderTrans_UID)", serviceOrderTrans_UIDParameter);
        }
    
        [DbFunction("KOTEntities", "ED_GetVatInfo")]
        public virtual IQueryable<ED_GetVatInfo_Result> ED_GetVatInfo(Nullable<decimal> kOTTrans_UID)
        {
            var kOTTrans_UIDParameter = kOTTrans_UID.HasValue ?
                new ObjectParameter("KOTTrans_UID", kOTTrans_UID) :
                new ObjectParameter("KOTTrans_UID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ED_GetVatInfo_Result>("[KOTEntities].[ED_GetVatInfo](@KOTTrans_UID)", kOTTrans_UIDParameter);
        }
    
        [DbFunction("KOTEntities", "EHM_GetFIFO")]
        public virtual IQueryable<EHM_GetFIFO_Result> EHM_GetFIFO(Nullable<int> sVT_ID, Nullable<decimal> i_ID, Nullable<decimal> b, Nullable<decimal> aG_ID)
        {
            var sVT_IDParameter = sVT_ID.HasValue ?
                new ObjectParameter("SVT_ID", sVT_ID) :
                new ObjectParameter("SVT_ID", typeof(int));
    
            var i_IDParameter = i_ID.HasValue ?
                new ObjectParameter("I_ID", i_ID) :
                new ObjectParameter("I_ID", typeof(decimal));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("B", b) :
                new ObjectParameter("B", typeof(decimal));
    
            var aG_IDParameter = aG_ID.HasValue ?
                new ObjectParameter("AG_ID", aG_ID) :
                new ObjectParameter("AG_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<EHM_GetFIFO_Result>("[KOTEntities].[EHM_GetFIFO](@SVT_ID, @I_ID, @B, @AG_ID)", sVT_IDParameter, i_IDParameter, bParameter, aG_IDParameter);
        }
    
        [DbFunction("KOTEntities", "EHM_GetWAM")]
        public virtual IQueryable<EHM_GetWAM_Result> EHM_GetWAM(Nullable<int> sVT_ID, Nullable<decimal> i_ID, Nullable<decimal> b, Nullable<decimal> aG_ID)
        {
            var sVT_IDParameter = sVT_ID.HasValue ?
                new ObjectParameter("SVT_ID", sVT_ID) :
                new ObjectParameter("SVT_ID", typeof(int));
    
            var i_IDParameter = i_ID.HasValue ?
                new ObjectParameter("I_ID", i_ID) :
                new ObjectParameter("I_ID", typeof(decimal));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("B", b) :
                new ObjectParameter("B", typeof(decimal));
    
            var aG_IDParameter = aG_ID.HasValue ?
                new ObjectParameter("AG_ID", aG_ID) :
                new ObjectParameter("AG_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<EHM_GetWAM_Result>("[KOTEntities].[EHM_GetWAM](@SVT_ID, @I_ID, @B, @AG_ID)", sVT_IDParameter, i_IDParameter, bParameter, aG_IDParameter);
        }
    
        [DbFunction("KOTEntities", "EHM_GetWAM_Counter")]
        public virtual IQueryable<EHM_GetWAM_Counter_Result> EHM_GetWAM_Counter(Nullable<int> sVT_ID, Nullable<decimal> i_ID, Nullable<decimal> b, Nullable<decimal> aG_ID)
        {
            var sVT_IDParameter = sVT_ID.HasValue ?
                new ObjectParameter("SVT_ID", sVT_ID) :
                new ObjectParameter("SVT_ID", typeof(int));
    
            var i_IDParameter = i_ID.HasValue ?
                new ObjectParameter("I_ID", i_ID) :
                new ObjectParameter("I_ID", typeof(decimal));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("B", b) :
                new ObjectParameter("B", typeof(decimal));
    
            var aG_IDParameter = aG_ID.HasValue ?
                new ObjectParameter("AG_ID", aG_ID) :
                new ObjectParameter("AG_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<EHM_GetWAM_Counter_Result>("[KOTEntities].[EHM_GetWAM_Counter](@SVT_ID, @I_ID, @B, @AG_ID)", sVT_IDParameter, i_IDParameter, bParameter, aG_IDParameter);
        }
    
        [DbFunction("KOTEntities", "EHM_GetWAMForISSUE")]
        public virtual IQueryable<EHM_GetWAMForISSUE_Result> EHM_GetWAMForISSUE(Nullable<int> sVT_ID, Nullable<decimal> i_ID, Nullable<decimal> b, Nullable<decimal> aG_ID)
        {
            var sVT_IDParameter = sVT_ID.HasValue ?
                new ObjectParameter("SVT_ID", sVT_ID) :
                new ObjectParameter("SVT_ID", typeof(int));
    
            var i_IDParameter = i_ID.HasValue ?
                new ObjectParameter("I_ID", i_ID) :
                new ObjectParameter("I_ID", typeof(decimal));
    
            var bParameter = b.HasValue ?
                new ObjectParameter("B", b) :
                new ObjectParameter("B", typeof(decimal));
    
            var aG_IDParameter = aG_ID.HasValue ?
                new ObjectParameter("AG_ID", aG_ID) :
                new ObjectParameter("AG_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<EHM_GetWAMForISSUE_Result>("[KOTEntities].[EHM_GetWAMForISSUE](@SVT_ID, @I_ID, @B, @AG_ID)", sVT_IDParameter, i_IDParameter, bParameter, aG_IDParameter);
        }
    
        [DbFunction("KOTEntities", "FN_Date")]
        public virtual IQueryable<FN_Date_Result> FN_Date(string fromdate, string toDate)
        {
            var fromdateParameter = fromdate != null ?
                new ObjectParameter("Fromdate", fromdate) :
                new ObjectParameter("Fromdate", typeof(string));
    
            var toDateParameter = toDate != null ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_Date_Result>("[KOTEntities].[FN_Date](@Fromdate, @ToDate)", fromdateParameter, toDateParameter);
        }
    
        [DbFunction("KOTEntities", "FN_GetEazyMasterPartnerInfo")]
        public virtual IQueryable<FN_GetEazyMasterPartnerInfo_Result> FN_GetEazyMasterPartnerInfo(Nullable<System.DateTime> masterSyncDate, Nullable<decimal> branchID, string currentDate)
        {
            var masterSyncDateParameter = masterSyncDate.HasValue ?
                new ObjectParameter("MasterSyncDate", masterSyncDate) :
                new ObjectParameter("MasterSyncDate", typeof(System.DateTime));
    
            var branchIDParameter = branchID.HasValue ?
                new ObjectParameter("BranchID", branchID) :
                new ObjectParameter("BranchID", typeof(decimal));
    
            var currentDateParameter = currentDate != null ?
                new ObjectParameter("CurrentDate", currentDate) :
                new ObjectParameter("CurrentDate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_GetEazyMasterPartnerInfo_Result>("[KOTEntities].[FN_GetEazyMasterPartnerInfo](@MasterSyncDate, @BranchID, @CurrentDate)", masterSyncDateParameter, branchIDParameter, currentDateParameter);
        }
    
        [DbFunction("KOTEntities", "FN_GetTotalDeductionForItemWiseST")]
        public virtual IQueryable<FN_GetTotalDeductionForItemWiseST_Result> FN_GetTotalDeductionForItemWiseST(Nullable<decimal> billTrans_UID)
        {
            var billTrans_UIDParameter = billTrans_UID.HasValue ?
                new ObjectParameter("BillTrans_UID", billTrans_UID) :
                new ObjectParameter("BillTrans_UID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_GetTotalDeductionForItemWiseST_Result>("[KOTEntities].[FN_GetTotalDeductionForItemWiseST](@BillTrans_UID)", billTrans_UIDParameter);
        }
    
        [DbFunction("KOTEntities", "FN_StringToTable")]
        public virtual IQueryable<FN_StringToTable_Result> FN_StringToTable(string str, string div)
        {
            var strParameter = str != null ?
                new ObjectParameter("Str", str) :
                new ObjectParameter("Str", typeof(string));
    
            var divParameter = div != null ?
                new ObjectParameter("Div", div) :
                new ObjectParameter("Div", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_StringToTable_Result>("[KOTEntities].[FN_StringToTable](@Str, @Div)", strParameter, divParameter);
        }
    
        [DbFunction("KOTEntities", "FN_WithoutKOTTableForTableGroup")]
        public virtual IQueryable<FN_WithoutKOTTableForTableGroup_Result> FN_WithoutKOTTableForTableGroup(Nullable<decimal> branch_UID, Nullable<decimal> hallUID)
        {
            var branch_UIDParameter = branch_UID.HasValue ?
                new ObjectParameter("Branch_UID", branch_UID) :
                new ObjectParameter("Branch_UID", typeof(decimal));
    
            var hallUIDParameter = hallUID.HasValue ?
                new ObjectParameter("HallUID", hallUID) :
                new ObjectParameter("HallUID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<FN_WithoutKOTTableForTableGroup_Result>("[KOTEntities].[FN_WithoutKOTTableForTableGroup](@Branch_UID, @HallUID)", branch_UIDParameter, hallUIDParameter);
        }
    }
}
