//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOTItemSentDetail
    {
        public int KOTDet_UID { get; set; }
        public int Waiter_UID { get; set; }
        public System.DateTime SentTime { get; set; }
        public int Quantity { get; set; }
        public int Status_UID { get; set; }
    }
}
