//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOTTransList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KOTTransList()
        {
            this.KOTTransList_AddOnsList = new HashSet<KOTTransList_AddOnsList>();
            this.KOTTransList_DiscountList = new HashSet<KOTTransList_DiscountList>();
            this.KOTTransList_Extn = new HashSet<KOTTransList_Extn>();
        }
    
        public decimal UID { get; set; }
        public decimal KOTTrans_UID { get; set; }
        public decimal ItemsM_UID { get; set; }
        public decimal UOM_UID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public decimal Price { get; set; }
        public System.DateTime OrderTime { get; set; }
        public decimal Value { get; set; }
        public decimal StatusM_UID { get; set; }
        public string Remarks { get; set; }
        public bool IsDelivered { get; set; }
        public bool FromDevice { get; set; }
        public string Instructions { get; set; }
        public bool IsParcelItem { get; set; }
        public bool IsComplement { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.DateTime> BatchDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public decimal ContainerM_UID { get; set; }
        public decimal Container_Value { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOTTransList_AddOnsList> KOTTransList_AddOnsList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOTTransList_DiscountList> KOTTransList_DiscountList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOTTransList_Extn> KOTTransList_Extn { get; set; }
    }
}
