//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class KOTTransList_Extn
    {
        public decimal UID { get; set; }
        public decimal KOTTransList_UID { get; set; }
        public System.DateTime OrderdTime { get; set; }
        public Nullable<System.DateTime> PreparedTime { get; set; }
        public Nullable<System.DateTime> DeliverdTime { get; set; }
        public decimal StatusM_UID { get; set; }
        public Nullable<decimal> Captain_UID { get; set; }
        public Nullable<decimal> Waiter_UID { get; set; }
        public string ChefName { get; set; }
        public Nullable<decimal> Chef_UID { get; set; }
        public Nullable<System.DateTime> ReadTime { get; set; }
        public Nullable<decimal> KOTMemoQueueLink_ID { get; set; }
        public Nullable<decimal> ExtendedPrepareTime { get; set; }
    
        public virtual KOTTransList KOTTransList { get; set; }
    }
}
