//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginDetail
    {
        public decimal UID { get; set; }
        public decimal Hall_UID { get; set; }
        public decimal User_UID { get; set; }
        public System.DateTime LoginDate { get; set; }
        public bool Status { get; set; }
        public string ComputerName { get; set; }
        public System.DateTime LoginTime { get; set; }
        public System.DateTime LogOutTime { get; set; }
        public decimal WorkingHours { get; set; }
        public decimal PayHours { get; set; }
        public string HoursEditReason { get; set; }
        public decimal InApprovedBy { get; set; }
        public decimal OutApprovedBy { get; set; }
    }
}
