//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Month
    {
        public int Month_No { get; set; }
        public string Month_Name { get; set; }
        public Nullable<int> Month_Quarter { get; set; }
        public Nullable<int> LedgerYr { get; set; }
        public int SortOrder { get; set; }
    }
}
