//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIbs_AssignOffer
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int OfferId { get; set; }
    
        public virtual Nibs_Offer Nibs_Offer { get; set; }
        public virtual tblOutlet tblOutlet { get; set; }
    }
}
