//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nibs_HappyHoursDates
    {
        public int HHDatesId { get; set; }
        public string HHOfferType { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int FreeItemId { get; set; }
        public decimal Discount { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public System.TimeSpan TimeEnd { get; set; }
        public int OfferId { get; set; }
        public Nullable<int> ItemIndex { get; set; }
    
        public virtual Nibs_Offer Nibs_Offer { get; set; }
        public virtual tblItem tblItem { get; set; }
    }
}
