//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenFood
    {
        public int Id { get; set; }
        public string ItemName { get; set; }
        public decimal Price { get; set; }
        public decimal Vat { get; set; }
        public System.DateTime Date { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> OutletId { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
