//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTransAttachment
    {
        public decimal UID { get; set; }
        public decimal OrderTrans_UID { get; set; }
        public decimal AttachmentTypeId { get; set; }
        public string FileName { get; set; }
        public string Searchkeyword { get; set; }
        public System.DateTime AttachmentDate { get; set; }
        public byte[] FileData { get; set; }
        public string Remarks { get; set; }
        public int StatusM_UID { get; set; }
    }
}
