//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTransHallDetail
    {
        public decimal UID { get; set; }
        public decimal OrderTrans_UID { get; set; }
        public decimal HallAccountM_UID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public decimal StatusM_UID { get; set; }
        public bool IsHall { get; set; }
        public System.DateTime FromTime { get; set; }
        public System.DateTime ToTime { get; set; }
    }
}
