//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTrans_MultiTemplateLink
    {
        public decimal UID { get; set; }
        public decimal OrderTrans_UID { get; set; }
        public decimal TemplateM_UID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Place { get; set; }
        public string AddlDetails { get; set; }
        public string Remarks { get; set; }
        public string ModeofTransport { get; set; }
        public int NoOfPerson { get; set; }
    }
}
