//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTransListLink
    {
        public decimal UID { get; set; }
        public decimal OrderTransList_UID { get; set; }
        public decimal RefOrderTransList_UID { get; set; }
        public decimal Qty { get; set; }
        public decimal AccountMItemsBOM_UID { get; set; }
        public decimal AvgPrice { get; set; }
    }
}
