//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherSettings_ExtnHistory
    {
        public decimal UID { get; set; }
        public bool ItemDeliveryChefflowNeeded { get; set; }
        public string ImageSizeinBytes { get; set; }
        public bool SmsforOrderReceived { get; set; }
        public bool Automaticzreportclosing { get; set; }
        public bool SmsforDelivered { get; set; }
        public decimal OrderUploadTime { get; set; }
        public bool CallCenterApplication { get; set; }
        public decimal AutoDeliveryupdatetime { get; set; }
        public bool DiscountApprovedbyManager { get; set; }
        public bool ChangeAddOn { get; set; }
        public string AutoZReportPath { get; set; }
        public bool DirectBillNeeded { get; set; }
        public bool SmalliconsinTablelist { get; set; }
        public bool Showorderslistmode { get; set; }
        public bool Rightsfordeleteitemafterbilling { get; set; }
        public bool ChefAppItemDeleteBefBill { get; set; }
        public bool MultipleCurrencyOptionNeeded { get; set; }
        public int KOTHallSeletionMode { get; set; }
        public bool EmployeeAttendenceDetailsNeeded { get; set; }
        public bool DefaultFontsizeNeeded { get; set; }
        public bool IsDisplayorderinLCD { get; set; }
        public decimal Charactercount { get; set; }
        public string LCDDisplayMessage { get; set; }
        public string LCDPort { get; set; }
        public bool IsBarcodeNeeded { get; set; }
        public bool DirectItemSelectionInCounterSales { get; set; }
        public bool IsTokenSalesNeeded { get; set; }
        public bool ExternalDataProcessNeeded { get; set; }
        public string ExternalDataProcessDBName { get; set; }
        public string ExternalDataProcessExePath { get; set; }
        public bool NoOfPersonsCountNeededInTakeAway { get; set; }
        public bool KOTNeededForTakeAway { get; set; }
        public bool DoorDeliveryAdditionalBillPrintNeeded { get; set; }
        public bool SuppressedItemKOTNeeded { get; set; }
        public bool LoginUserVisiblity { get; set; }
        public bool ColorChangesNeededForDoorDelivery { get; set; }
        public decimal PickupdeliveryTime { get; set; }
        public bool RemarksNeededinBillPrint { get; set; }
        public bool NextCustomerNeeded { get; set; }
        public bool ItemWiseServiceTaxNeeded { get; set; }
        public bool CommissionMasterNeeded { get; set; }
        public bool TransferBillNeeded { get; set; }
        public bool TaxBreakupNeeded { get; set; }
        public bool ZreportAutoGenForAccounts { get; set; }
        public bool AutoCashSettlementForAccounts { get; set; }
        public string LCDFooterMessage { get; set; }
        public bool SAPPostingNeeded { get; set; }
        public decimal FranchisePer { get; set; }
        public int ItemSearchBasedOn { get; set; }
        public bool SingleKOTMemoForSuppress { get; set; }
        public bool WaiterNeededinTakeAwayPrint { get; set; }
        public int DoordeliveryHall_PrintCount { get; set; }
        public string EstimationCaption { get; set; }
        public bool UseEachPCforEachLineNo { get; set; }
        public bool RefreshFoodAvailability { get; set; }
        public bool IsRetail { get; set; }
        public int UseFIFOForBatchSelection { get; set; }
        public bool IsRapidMode { get; set; }
        public bool BarcodeNeededforCollection { get; set; }
        public bool ItemWiseServiceChargeNeeded { get; set; }
        public string ItemBarcode_Delimiter { get; set; }
        public bool ServiceChargesAddWithServiceTax { get; set; }
        public bool EnabledTableClean { get; set; }
        public decimal TableCleanTime { get; set; }
        public bool ShowTakeAwayInChefDisplay { get; set; }
        public bool AutoItemAvailabilityUpdate { get; set; }
        public bool DisplayPopupForReadyItem { get; set; }
        public bool UseMultiLineDevice { get; set; }
        public string NonChargeableDescription { get; set; }
        public bool EasyMaster_StockUpdate { get; set; }
        public bool BarcodeNeededforKOTMemo { get; set; }
        public bool DirectCollectionoptionNeeded { get; set; }
        public bool AutomaticCollectasCash { get; set; }
        public int UploadRowCount { get; set; }
        public bool PaymentOptionNeeded { get; set; }
        public bool PromoMasterNeeded { get; set; }
        public string PromoFilePath { get; set; }
        public bool eKOTNeeded { get; set; }
        public decimal eKOTUpdatetime { get; set; }
        public bool CashonDeliveryNeeded { get; set; }
        public bool OtherPaymentNeeded { get; set; }
        public bool DoorDeliveryNeeded { get; set; }
        public bool PickupNeeded { get; set; }
        public bool SpecialMenuTemplateNeeded { get; set; }
        public bool AutomaticDeliveryNeeded { get; set; }
        public bool PaymentIntegrationNeeded { get; set; }
        public string EazyOrderURL { get; set; }
        public string ParcelDescription { get; set; }
        public decimal ItemImageWidth { get; set; }
        public decimal ItemImageHeight { get; set; }
        public bool EnableLoyalty { get; set; }
        public decimal LoyaltySalesAmount { get; set; }
        public decimal LoyaltySalesPoints { get; set; }
        public decimal LoyaltyRedeemAmount { get; set; }
        public decimal LoyaltyRedeemPoints { get; set; }
    }
}
