//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtherSettingshistory
    {
        public decimal UID { get; set; }
        public bool ShiftNeeded { get; set; }
        public bool CaptainNeeded { get; set; }
        public bool KOTSerialNumberNeeded { get; set; }
        public bool SingleKotforSubGroupPrint { get; set; }
        public bool PrintPreviewNeeded { get; set; }
        public bool ItemWiseVATNeeded { get; set; }
        public bool TableWiseWaiterSelectionNeeded { get; set; }
        public bool ItemWiseCalcNeeded { get; set; }
        public bool DiscountByPer { get; set; }
        public string BackUpLocation { get; set; }
        public int Interval { get; set; }
        public System.DateTime LastBackUpTime { get; set; }
        public bool ServiceChargeNeeded { get; set; }
        public decimal ServiceChargePer { get; set; }
        public bool CustomerSelection { get; set; }
        public bool SumofQtyNeeded { get; set; }
        public bool HallWiseBillNo { get; set; }
        public bool PrinterInfo { get; set; }
        public int QOHType { get; set; }
        public bool RemoveData { get; set; }
        public int DaystoKept { get; set; }
        public bool CapConInTakeaway { get; set; }
        public bool NewItemOrder { get; set; }
        public bool KOTPrintByRegion { get; set; }
        public bool BillPrintByRegion { get; set; }
        public int KOTFontSize { get; set; }
        public int RegionalID { get; set; }
        public Nullable<bool> DeliveryProcessNeeded { get; set; }
        public bool CounterSales { get; set; }
        public bool ItemEditing { get; set; }
        public string FamilyType { get; set; }
        public string FontName { get; set; }
        public bool IsStandAlone { get; set; }
        public bool RegionalFontDisplay { get; set; }
        public bool TenderAmtNeeded { get; set; }
        public bool CounterMemoPrint { get; set; }
        public bool PostTableGrouping { get; set; }
        public bool SecondLinePrint { get; set; }
        public int DelayinSec { get; set; }
        public int AllowCancel { get; set; }
        public bool TakeawayCustomerInfo { get; set; }
        public bool PreprationTimeNeeded { get; set; }
        public decimal PreprationTime { get; set; }
        public bool CashCollectionNeeded { get; set; }
        public decimal MemoInterval { get; set; }
        public decimal TakeAwayInterval { get; set; }
        public decimal TableRefreshIntrvl { get; set; }
        public bool CashasDefault { get; set; }
        public bool DirectlyStockReduceFromDine { get; set; }
        public bool OpenCashDrawerPaySubmit { get; set; }
        public bool DiscountPreconfigured { get; set; }
        public string Discountvalues { get; set; }
        public bool DirectCollectioninTakeaway { get; set; }
        public string CalculateDiscountfor { get; set; }
        public bool AdditionalBillPrinttakeaway { get; set; }
        public bool WaiterBasedEntrywithBill { get; set; }
        public bool UserrightsvalidationXReport { get; set; }
        public bool ReupdateCollection { get; set; }
        public bool HallGroupWiseBillNoGeneration { get; set; }
        public bool IsWeighmentRequired { get; set; }
        public bool IsCompensationFactor { get; set; }
        public bool NeedAreaMaster { get; set; }
        public bool RoomServiceDetailsNeeded { get; set; }
        public string BillnoCaption { get; set; }
        public bool PrintHallNameatTop { get; set; }
        public bool PrintCurrencyinBillTotal { get; set; }
        public bool BarcodeIntegrationNeeded { get; set; }
        public bool Reupdatecollectiondetailsneeded { get; set; }
        public bool IsneededItemwiseCaptainorWaiter { get; set; }
        public string ServiceOrderCloudCredential { get; set; }
        public string ServiceOrderSyncFolder { get; set; }
        public bool SelfServiceOrderFlowNeeded { get; set; }
        public bool PrintAddonItemsinBill { get; set; }
        public bool DeliveryTrackingNeededForTakeAway { get; set; }
        public bool TipandGuestnameonBillPrint { get; set; }
        public bool Onlineorderneeded { get; set; }
        public string CloudAPIURL { get; set; }
        public string CloudBranchName { get; set; }
        public bool LoginPunchNeeded { get; set; }
        public bool Settingsmode { get; set; }
        public bool EnableOrderDirectly { get; set; }
        public bool EnableCaptainCumWaiter { get; set; }
        public bool UseTouchforQty { get; set; }
        public bool RegionalLanguageinallscreen { get; set; }
        public string Cloudfilechanges { get; set; }
        public string CloudSourceFileURL { get; set; }
        public decimal OnlineOrderBranchUID { get; set; }
        public string CloudPassword { get; set; }
        public string CloudPartnerID { get; set; }
    }
}
