//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutletVendor
    {
        public OutletVendor()
        {
            this.SelesVendorAmounts = new HashSet<SelesVendorAmount>();
            this.SelesVendorAmountDetails = new HashSet<SelesVendorAmountDetail>();
            this.Temp_VendorBilling = new HashSet<Temp_VendorBilling>();
            this.VendorBillingMasters = new HashSet<VendorBillingMaster>();
            this.VendorPrices = new HashSet<VendorPrice>();
        }
    
        public int OutletVenderId { get; set; }
        public int OutletId { get; set; }
        public string VenderName { get; set; }
        public string VenderContact { get; set; }
        public string VendorEmail { get; set; }
        public string VendorAddress { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblOutlet tblOutlet { get; set; }
        public virtual ICollection<SelesVendorAmount> SelesVendorAmounts { get; set; }
        public virtual ICollection<SelesVendorAmountDetail> SelesVendorAmountDetails { get; set; }
        public virtual ICollection<Temp_VendorBilling> Temp_VendorBilling { get; set; }
        public virtual ICollection<VendorBillingMaster> VendorBillingMasters { get; set; }
        public virtual ICollection<VendorPrice> VendorPrices { get; set; }
    }
}
