//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentGatewayM
    {
        public System.Guid UID { get; set; }
        public string PaymentGatewayType { get; set; }
        public string PaymentGatewayName { get; set; }
        public string PaymentIconName { get; set; }
        public string RequestURL { get; set; }
        public bool IsActive { get; set; }
    }
}
