//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTypeM
    {
        public System.Guid PaymentTypeUID { get; set; }
        public int SlNo { get; set; }
        public string PaymentTypeCode { get; set; }
        public string PaymentTypeDescription { get; set; }
        public bool IsActive { get; set; }
    }
}
