//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceListEntryHistory
    {
        public decimal UID { get; set; }
        public decimal PriceListEntry_UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal AccountM_UID { get; set; }
        public decimal AccountMItems_UID { get; set; }
        public decimal Price { get; set; }
        public decimal OldPrice { get; set; }
        public decimal UOM_UID { get; set; }
        public decimal UOM_Rate { get; set; }
        public string ModifiedReason { get; set; }
        public string ModifiedUser { get; set; }
        public decimal ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual PriceListEntry PriceListEntry { get; set; }
    }
}
