//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promo_Validity
    {
        public decimal UID { get; set; }
        public decimal Promo_Header_UID { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public System.DateTime FromTime { get; set; }
        public System.DateTime ToTime { get; set; }
        public string DayApplicable { get; set; }
        public string ValidityType { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Promo_Header Promo_Header { get; set; }
    }
}
