//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promo_BOGO_Header
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Promo_BOGO_Header()
        {
            this.Promo_BOGO_List = new HashSet<Promo_BOGO_List>();
        }
    
        public decimal UID { get; set; }
        public decimal Promo_Header_UID { get; set; }
        public decimal AccountMItems_UID { get; set; }
        public decimal MinQty { get; set; }
        public decimal MaxQty { get; set; }
        public int FreeItemCount { get; set; }
        public string BOGOType { get; set; }
        public string BOGO_Offer_Desc { get; set; }
    
        public virtual AccountMItem AccountMItem { get; set; }
        public virtual Promo_Header Promo_Header { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promo_BOGO_List> Promo_BOGO_List { get; set; }
    }
}
