//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promo_BOGO_List
    {
        public decimal UID { get; set; }
        public decimal Promo_BOGO_Header_UID { get; set; }
        public decimal AccountMItems_UID { get; set; }
        public decimal ByPercentage { get; set; }
        public decimal ByValue { get; set; }
        public decimal Promo_Header_UID { get; set; }
    
        public virtual Promo_BOGO_Header Promo_BOGO_Header { get; set; }
        public virtual Promo_Header Promo_Header { get; set; }
    }
}
