//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawCategory
    {
        public RawCategory()
        {
            this.tbl_RawMaterials = new HashSet<tbl_RawMaterials>();
            this.AddCategoryVendors = new HashSet<AddCategoryVendor>();
        }
    
        public int RawCategoryID { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<tbl_RawMaterials> tbl_RawMaterials { get; set; }
        public virtual ICollection<AddCategoryVendor> AddCategoryVendors { get; set; }
    }
}
