//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reconciliation
    {
        public decimal UID { get; set; }
        public System.DateTime ClearanceDate { get; set; }
        public string Remarks { get; set; }
        public decimal AccountM_UID { get; set; }
        public int FinYear { get; set; }
        public decimal PC_UID { get; set; }
        public decimal OpeningBalDr { get; set; }
        public decimal ClosingBalDr { get; set; }
        public decimal OpeningBalCr { get; set; }
        public decimal ClosingBalCr { get; set; }
    }
}
