//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBillTransList
    {
        public decimal UID { get; set; }
        public decimal RoomBillTrans_UID { get; set; }
        public decimal RoomsM_UID { get; set; }
        public decimal NoOfRooms { get; set; }
        public decimal NoOfDays { get; set; }
        public decimal TariffRent { get; set; }
        public decimal Total { get; set; }
        public decimal ServTaxPer { get; set; }
        public decimal ServTaxAmount { get; set; }
        public decimal ServChargePer { get; set; }
        public decimal ServChargeAmount { get; set; }
        public decimal Discount { get; set; }
        public decimal NettTotal { get; set; }
        public decimal TaxMaster_UID { get; set; }
        public decimal CessPer { get; set; }
        public decimal CessAmount { get; set; }
        public decimal HECEssPer { get; set; }
        public decimal HECEssAmount { get; set; }
        public decimal Rooms_ServiceUID { get; set; }
        public decimal AddlCharge_UID { get; set; }
    
        public virtual RoomBillTran RoomBillTran { get; set; }
        public virtual RoomsM RoomsM { get; set; }
    }
}
