//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomAllocation_Dine
    {
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal RoomUID { get; set; }
        public decimal GuestUID { get; set; }
        public System.DateTime CheckInDateTime { get; set; }
        public Nullable<System.DateTime> CheckOutDateTime { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
