//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomsM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomsM()
        {
            this.RoomAllocationLists = new HashSet<RoomAllocationList>();
            this.RoomBillTransLists = new HashSet<RoomBillTransList>();
            this.RoomReservationLists = new HashSet<RoomReservationList>();
            this.ServiceBillLists = new HashSet<ServiceBillList>();
        }
    
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public string RoomNo { get; set; }
        public Nullable<decimal> RoomType_UID { get; set; }
        public string FloorDetails { get; set; }
        public string Direction { get; set; }
        public string Location { get; set; }
        public string Side { get; set; }
        public string FacilityAvailable { get; set; }
        public byte[] Photograph { get; set; }
        public Nullable<decimal> TariffRent { get; set; }
        public Nullable<decimal> Disc_Allowed { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public int NoOfBeds { get; set; }
        public decimal ExtraBedCharge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomAllocationList> RoomAllocationLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomBillTransList> RoomBillTransLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomReservationList> RoomReservationLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceBillList> ServiceBillLists { get; set; }
    }
}
