//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomReservationTran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomReservationTran()
        {
            this.RoomReservationAdvances = new HashSet<RoomReservationAdvance>();
            this.RoomReservationLists = new HashSet<RoomReservationList>();
        }
    
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public Nullable<decimal> GuestsM_UID { get; set; }
        public string GuestName { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public System.DateTime CheckInDateTime { get; set; }
        public System.DateTime CheckOutDateTime { get; set; }
        public int NumberOfRooms { get; set; }
        public int NumberOfPersons { get; set; }
        public string AddlNotes { get; set; }
        public decimal StatusM_UID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> Incharge_UID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomReservationAdvance> RoomReservationAdvances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomReservationList> RoomReservationLists { get; set; }
    }
}
