//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTariffMapping
    {
        public decimal UID { get; set; }
        public decimal RoomID { get; set; }
        public decimal CategoryID { get; set; }
        public decimal CategoryTypeID { get; set; }
        public decimal TariffAmt { get; set; }
    }
}
