//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_EDI_DC40
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAP_EDI_DC40()
        {
            this.SAP_E1KOMG = new HashSet<SAP_E1KOMG>();
            this.SAP_E1WPA01 = new HashSet<SAP_E1WPA01>();
            this.SAP_E1WPW01 = new HashSet<SAP_E1WPW01>();
        }
    
        public decimal SAP_EDI_DC40_Id { get; set; }
        public string TABNAM { get; set; }
        public string MANDT { get; set; }
        public string DOCNUM { get; set; }
        public string DOCREL { get; set; }
        public string STATUS { get; set; }
        public string DIRECT { get; set; }
        public string OUTMOD { get; set; }
        public string IDOCTYP { get; set; }
        public string MESTYP { get; set; }
        public string SNDPOR { get; set; }
        public string SNDPRT { get; set; }
        public string SNDPRN { get; set; }
        public string RCVPOR { get; set; }
        public string RCVPRT { get; set; }
        public string RCVPRN { get; set; }
        public string CREDAT { get; set; }
        public string CRETIM { get; set; }
        public string SERIAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAP_E1KOMG> SAP_E1KOMG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAP_E1WPA01> SAP_E1WPA01 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAP_E1WPW01> SAP_E1WPW01 { get; set; }
    }
}
