//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_E1KONH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAP_E1KONH()
        {
            this.SAP_E1KONP = new HashSet<SAP_E1KONP>();
        }
    
        public decimal SAP_E1KONH_Id { get; set; }
        public Nullable<decimal> SAP_E1KOMG_Id { get; set; }
        public string KNUMH { get; set; }
        public string DATAB { get; set; }
        public string DATBI { get; set; }
        public string KNUMA_PI { get; set; }
        public Nullable<decimal> E1KONH_Id { get; set; }
    
        public virtual SAP_E1KOMG SAP_E1KOMG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAP_E1KONP> SAP_E1KONP { get; set; }
    }
}
