//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_E1KONP
    {
        public decimal SAP_E1KONP1 { get; set; }
        public Nullable<decimal> SAP_E1KONH_Id { get; set; }
        public string KSCHL { get; set; }
        public string STFKZ { get; set; }
        public string KSTBM { get; set; }
        public string KSTBW { get; set; }
        public string KRECH { get; set; }
        public Nullable<decimal> KBETR { get; set; }
        public string KONWA { get; set; }
        public string KPEIN { get; set; }
        public string KMEIN { get; set; }
        public string KUMZA { get; set; }
        public string KUMNE { get; set; }
        public string MXWRT { get; set; }
        public string GKWRT { get; set; }
        public string ZAEHK_IND { get; set; }
        public string KBRUE { get; set; }
        public string VALTG { get; set; }
        public string VALDT { get; set; }
        public string ANZAUF { get; set; }
        public string MIKBAS { get; set; }
        public string MXKBAS { get; set; }
        public string KOMXWRT { get; set; }
        public string KLF_STG { get; set; }
        public string KLF_KAL { get; set; }
    
        public virtual SAP_E1KONH SAP_E1KONH { get; set; }
    }
}
