//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_E1WPA02
    {
        public decimal SAP_E1WPA02_Id { get; set; }
        public Nullable<decimal> SAP_E1WPA01_Id { get; set; }
        public string WARENGR { get; set; }
        public string VERPGEW { get; set; }
        public string VKINPERFOR { get; set; }
        public string RABERLAUBT { get; set; }
        public string PRDRUCK { get; set; }
        public string ARTIKANZ { get; set; }
        public string MHDRZ { get; set; }
        public string MHDHB { get; set; }
    
        public virtual SAP_E1WPA01 SAP_E1WPA01 { get; set; }
    }
}
