//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_E1WPA01
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAP_E1WPA01()
        {
            this.SAP_E1WPA02 = new HashSet<SAP_E1WPA02>();
            this.SAP_E1WPA03 = new HashSet<SAP_E1WPA03>();
            this.SAP_E1WXX01 = new HashSet<SAP_E1WXX01>();
        }
    
        public decimal SAP_E1WPA01_Id { get; set; }
        public Nullable<decimal> SAP_EDI_DC40_Id { get; set; }
        public string FILIALE { get; set; }
        public string AENDKENNZ { get; set; }
        public string AKTIVDATUM { get; set; }
        public string AENDDATUM { get; set; }
        public string HAUPTEAN { get; set; }
        public string ARTIKELNR { get; set; }
        public string POSME { get; set; }
        public Nullable<decimal> E1WPA01_Id { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<System.DateTime> UpdatedTime { get; set; }
    
        public virtual SAP_EDI_DC40 SAP_EDI_DC40 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAP_E1WPA02> SAP_E1WPA02 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAP_E1WPA03> SAP_E1WPA03 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAP_E1WXX01> SAP_E1WXX01 { get; set; }
    }
}
