//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAP_E1WXX01
    {
        public decimal SAP_E1WXX01_Id { get; set; }
        public Nullable<decimal> SAP_E1WPA01_Id { get; set; }
        public string FLDGRP { get; set; }
        public string FLDNAME { get; set; }
        public string FLDVAL { get; set; }
    
        public virtual SAP_E1WPA01 SAP_E1WPA01 { get; set; }
    }
}
