//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPAdvancePayment
    {
        public decimal UID { get; set; }
        public System.DateTime AdvanceDate { get; set; }
        public string CustomerName { get; set; }
        public decimal PaymentType_UID { get; set; }
        public decimal Amount { get; set; }
        public decimal CreatedBy { get; set; }
    }
}
