//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPItemSubGroupDineGroupMapping
    {
        public decimal UID { get; set; }
        public string SAP_ItemSubGroupCode { get; set; }
        public Nullable<decimal> ItemSubGroup_UID { get; set; }
        public string SAP_ItemDineGroupCode { get; set; }
        public Nullable<decimal> ItemDineGroup_UID { get; set; }
    
        public virtual AccountM AccountM { get; set; }
        public virtual AccountM AccountM1 { get; set; }
    }
}
