//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelesVendorAmount
    {
        public int Id { get; set; }
        public int OutletId { get; set; }
        public int VendorId { get; set; }
        public decimal Amount { get; set; }
    
        public virtual tblOutlet tblOutlet { get; set; }
        public virtual OutletVendor OutletVendor { get; set; }
    }
}
