//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBillList
    {
        public decimal UID { get; set; }
        public decimal ServiceBillTrans_UID { get; set; }
        public decimal RoomsM_UID { get; set; }
        public decimal ServiceType_UID { get; set; }
        public string ServiceDescription { get; set; }
        public string RoomService { get; set; }
        public decimal ServiceCharge { get; set; }
        public decimal ServiceTaxPer { get; set; }
        public decimal ServiceTaxCharge { get; set; }
        public decimal NettTotal { get; set; }
        public decimal TaxMaster_UID { get; set; }
        public decimal CessPer { get; set; }
        public decimal CessAmount { get; set; }
        public decimal HECEssPer { get; set; }
        public decimal HECEssAmount { get; set; }
        public Nullable<int> NoOfPersons { get; set; }
    
        public virtual RoomsM RoomsM { get; set; }
        public virtual ServiceBillTran ServiceBillTran { get; set; }
    }
}
