//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrderPrintingQueue
    {
        public decimal UID { get; set; }
        public decimal BillTrans_UID { get; set; }
        public System.DateTime DeliverTime { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public Nullable<decimal> Branch_UID { get; set; }
    }
}
