//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceBillTran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceBillTran()
        {
            this.ServiceBillLists = new HashSet<ServiceBillList>();
        }
    
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal ServiceBillNo { get; set; }
        public System.DateTime ServiceBillDate { get; set; }
        public decimal GuestsM_UID { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public decimal Total { get; set; }
        public decimal TaxPer { get; set; }
        public decimal TaxTotal { get; set; }
        public decimal NettValue { get; set; }
        public string AddlNotes { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<decimal> ModifiedBy { get; set; }
        public decimal StatusM_UID { get; set; }
        public decimal ServedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceBillList> ServiceBillLists { get; set; }
    }
}
