//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceOrderTrans_TaxLink
    {
        public decimal UID { get; set; }
        public decimal ServiceOrderTrans_UID { get; set; }
        public decimal VAT_UID { get; set; }
        public string VATItemDetails { get; set; }
        public decimal VATAmount { get; set; }
    }
}
