//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettlementInfo
    {
        public decimal UID { get; set; }
        public System.DateTime DocDate { get; set; }
        public decimal Hall_UID { get; set; }
        public decimal Shift_UID { get; set; }
        public decimal Cashier_UID { get; set; }
        public decimal FromNo { get; set; }
        public decimal ToNo { get; set; }
        public decimal TotalSales { get; set; }
        public decimal NonChargeable { get; set; }
        public decimal CancelledBills { get; set; }
        public decimal GrandSales { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public decimal StatusM_UID { get; set; }
        public System.DateTime DeleteTime { get; set; }
        public decimal TotalBillCount { get; set; }
        public decimal CancelCount { get; set; }
    }
}
