//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsM
    {
        public decimal UID { get; set; }
        public bool IsAutoIssueNeeded { get; set; }
        public string EazyHMURL { get; set; }
        public bool IsAutoInspectionNeeded { get; set; }
        public bool IsBelowPriceTemplate { get; set; }
        public bool ManualClosingStockNeeded { get; set; }
        public bool InternalOrderMinandMaxQty { get; set; }
        public bool FoodDespatchAcrossBranchLock { get; set; }
        public bool IsSimpleInventoryNeeded { get; set; }
        public bool IsItemwiseTaxNeeded { get; set; }
        public bool IsCatering { get; set; }
        public bool DirectlyStockUpdatetoPOS { get; set; }
        public bool HideClosingStockFromBranch { get; set; }
        public bool AutoInternalReceiptNeeded { get; set; }
        public bool AutoGRNInspectionNeeded { get; set; }
        public bool SingleStoreNeeded { get; set; }
        public bool IsShowPriceandValueToBranch { get; set; }
        public bool IsShowOrderedQtyInGrid { get; set; }
        public bool IsShowUsernameinDocPrint { get; set; }
        public bool IsFreeItemNeeded { get; set; }
        public decimal PendingListDisplayDays { get; set; }
        public bool AllowBasicValueenter { get; set; }
        public bool BOMNotRequired { get; set; }
        public bool AutoFoodReceiptNeeded { get; set; }
        public bool SectionWiseIssueNeeded { get; set; }
        public bool DefaultTOBranchLoadedInBranchs { get; set; }
        public bool TemplateListsaveornot { get; set; }
        public bool ProductionAgainstInternalOrder { get; set; }
        public bool ProductionReceiptMPlookupselectall { get; set; }
        public bool AllowToEditGridQtyInLookup { get; set; }
        public bool SessionNeeded { get; set; }
        public bool OverProductionEntryNeeded { get; set; }
        public bool AllowExtraDespatchQty { get; set; }
        public bool ConversionBaseReport { get; set; }
        public bool DefaultQtyZeroInLookupGrid { get; set; }
        public bool SectionWiseIndentNeeded { get; set; }
        public bool AllowDirectProductionReceipt { get; set; }
        public bool AllowDirectDespatch { get; set; }
        public bool IndentSendMailNeeded { get; set; }
        public bool BackDateStockCorrectionNeeded { get; set; }
        public bool LoadItemcodeInLookupNeeded { get; set; }
        public bool DespatchPrintsendtoPrinter { get; set; }
        public bool RefDocDateBasedReportNeeded { get; set; }
        public bool IsBatchNeeded { get; set; }
        public bool IsDespatchConsolidateNeeded { get; set; }
        public bool HeaderWiseFindGridDisplay { get; set; }
        public bool PurchaseOrderSendMailNeeded { get; set; }
        public int DecimalsforPriceandAmount { get; set; }
        public bool PhysicalStockfetchfromDailyStockClosing { get; set; }
        public bool ExternalSettlementWastageConformNeeded { get; set; }
        public bool AutoTermsfillFromMasterInPO { get; set; }
        public bool AllowZeroPriceInPO { get; set; }
        public bool SaleInvoiceNeeded { get; set; }
        public bool LocalPurchaseandWastageUploadfromExcel { get; set; }
        public bool IsNewModeEnable { get; set; }
        public bool AutomaticSettlementNeeded { get; set; }
        public string SettlementFolder { get; set; }
        public string MachineName { get; set; }
        public bool Settlement_Zero_Price_Error { get; set; }
        public bool IsAutoStockAdjustment { get; set; }
        public bool AllowPurchaseOrderBackDate { get; set; }
        public bool IsItemStoreMappingNeeded { get; set; }
        public bool AllowBranchWiseROL { get; set; }
    }
}
