//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettlementDetail
    {
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal Hall_UID { get; set; }
        public decimal Cashier_UID { get; set; }
        public System.DateTime SettlementDate { get; set; }
        public System.DateTime SettlementTime { get; set; }
        public int SettlementNo { get; set; }
        public decimal SettlementAmount { get; set; }
        public decimal OpeningCash { get; set; }
        public decimal Cash { get; set; }
        public decimal Card { get; set; }
        public decimal Vouchers { get; set; }
        public decimal CreditSales { get; set; }
        public decimal CancelledBillsAmount { get; set; }
        public decimal SO_Cash { get; set; }
        public decimal SO_Card { get; set; }
        public decimal SO_Voucher { get; set; }
        public decimal CB_Cash { get; set; }
        public decimal CB_Card { get; set; }
        public decimal CB_Voucher { get; set; }
        public decimal UnCollected { get; set; }
        public Nullable<decimal> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedTime { get; set; }
        public decimal BillTrans_UID { get; set; }
        public decimal PaymentType_UID { get; set; }
        public decimal PettyCash_UID { get; set; }
        public decimal ServiceOrderPayment_UID { get; set; }
        public decimal CreditBillPayment_UID { get; set; }
        public decimal TotalSales { get; set; }
        public string Remarks { get; set; }
        public decimal ShiftM_UID { get; set; }
    }
}
