//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftMConfigurationHistory
    {
        public decimal UID { get; set; }
        public bool HallWise { get; set; }
        public bool JuiceMemo { get; set; }
        public bool ShiftChange { get; set; }
        public Nullable<decimal> MealsTokenLimit { get; set; }
        public bool OpenRateNeeded { get; set; }
        public bool IncPerformance { get; set; }
        public decimal IncValue { get; set; }
        public bool DataRefresh { get; set; }
        public Nullable<bool> WithOptimizer { get; set; }
        public bool DeviceKitchenPrint { get; set; }
        public bool IsPaymentTypeNeeded { get; set; }
        public bool IsSubGroupPrintNeeded { get; set; }
        public bool TimeNeededInPrint { get; set; }
        public int MemoPrintCount { get; set; }
        public decimal RefreshTime { get; set; }
        public Nullable<bool> IsShiftChangeNeeded { get; set; }
        public Nullable<bool> AdditionalInfoNeeded { get; set; }
        public Nullable<int> MemoTopSpace { get; set; }
        public Nullable<int> MemoBottomSpace { get; set; }
        public Nullable<bool> RoundOffNeeded { get; set; }
        public Nullable<bool> CaptainConfirmNeeded { get; set; }
        public Nullable<bool> CashReceivedPrint { get; set; }
        public bool TakeAwaySubGroupPrintNeeded { get; set; }
        public bool PriceNeededInPrint { get; set; }
        public bool ParcelOptionInPrint { get; set; }
        public string RemoteServerConnection { get; set; }
        public bool ServiceOrderNeeded { get; set; }
        public Nullable<decimal> CancelOrderBefore { get; set; }
        public int BluetoothPrint { get; set; }
        public int AddlCharges { get; set; }
        public bool AcceptItemSelectFirst { get; set; }
        public bool DiscountNeededInKOT { get; set; }
        public bool ReprintBillNeededInKOT { get; set; }
        public bool QOHCheckNeeded { get; set; }
        public bool CashInfoNeeded { get; set; }
        public bool PersonCountNeeded { get; set; }
        public int DataSyncType { get; set; }
        public bool DuplicateKOTMemoNeeded { get; set; }
        public string KMWebService { get; set; }
        public int KOTType { get; set; }
        public int CallWaiter { get; set; }
        public int QtyCountNeeded { get; set; }
        public int ServiceTaxType { get; set; }
        public string ReplicationServerName { get; set; }
        public Nullable<System.Guid> ReplicationUID { get; set; }
        public int VatType { get; set; }
        public string Reason { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool ShowRunDateTime { get; set; }
        public bool QSRbasedstockflow { get; set; }
        public bool ContinuousBillNoGeneration { get; set; }
        public int KOTprintingorder { get; set; }
        public bool Iscallcenter { get; set; }
        public decimal DefaultTakeawayHall { get; set; }
        public bool PrintmultipleTokens { get; set; }
        public bool CashFlowNeeded { get; set; }
        public bool HundredPerDiscount { get; set; }
        public int KotItemPrintOrder { get; set; }
        public bool CSTPrintrequiredonBill { get; set; }
        public bool ShowBillPrint { get; set; }
        public bool PriceNeededinTokenmemo { get; set; }
        public bool Showtakeawaydoordeliveryinbill { get; set; }
        public int DecimalsforPriceandAmount { get; set; }
        public bool QtyNeededinmemoPrint { get; set; }
        public bool UservalidationforcancelledBill { get; set; }
        public bool EmployeeSettlementDetailsNeeded { get; set; }
    }
}
