//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShiftM_Current
    {
        public decimal Branch_UID { get; set; }
        public decimal Department_UID { get; set; }
        public System.DateTime ShiftDate { get; set; }
        public decimal ShiftM_UID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public decimal StatusM_UID { get; set; }
    }
}
