//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SqlpatchUpdatestatu
    {
        public decimal PatchID { get; set; }
        public string AppName { get; set; }
        public System.DateTime PatchDate { get; set; }
        public string ReleasedBy { get; set; }
        public bool Approved { get; set; }
        public string AddlNotes { get; set; }
        public string FileName { get; set; }
        public string SqlPatch { get; set; }
    }
}
