//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransListRejection
    {
        public decimal UID { get; set; }
        public decimal StockTransList_UID { get; set; }
        public decimal Rejection_UID { get; set; }
        public decimal Qty { get; set; }
        public decimal BalanceQty { get; set; }
        public string AddlNotes { get; set; }
        public int StatusM_UID { get; set; }
    }
}
