//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransListContainer
    {
        public decimal UID { get; set; }
        public decimal ContainerM_UID { get; set; }
        public decimal AccountMGroups_UID { get; set; }
        public decimal RefAccountMGroups_UID { get; set; }
        public decimal StockTrans_UID { get; set; }
        public decimal StockTransList_UID { get; set; }
        public decimal AccountMItemsM_UID { get; set; }
        public decimal Container_Weight { get; set; }
        public decimal Gross_Weight { get; set; }
        public Nullable<decimal> Nett_Weight { get; set; }
        public bool IsReceipt { get; set; }
        public bool IsClosed { get; set; }
        public decimal RefStockTransListContainer_UID { get; set; }
        public decimal ModeofTransport_UID { get; set; }
        public decimal LocationID { get; set; }
        public string BatchNumber { get; set; }
        public decimal Rejected_Weight { get; set; }
    }
}
