//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransListHistory
    {
        public decimal UID { get; set; }
        public decimal StockTransList_UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal AccountMGroups_UID { get; set; }
        public decimal StockTrans_UID { get; set; }
        public decimal Items_UID { get; set; }
        public decimal UOM_UID { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> BasicValue { get; set; }
        public decimal BasicDiscountPer { get; set; }
        public Nullable<decimal> BasicDiscountAmount { get; set; }
        public decimal PackingPer { get; set; }
        public Nullable<decimal> PackingAmount { get; set; }
        public decimal EDID { get; set; }
        public decimal EDPer { get; set; }
        public Nullable<decimal> EDAmount { get; set; }
        public decimal CessID { get; set; }
        public decimal CessPer { get; set; }
        public Nullable<decimal> CessAmount { get; set; }
        public decimal HECessID { get; set; }
        public decimal HECessPer { get; set; }
        public Nullable<decimal> HECessAmount { get; set; }
        public decimal VATCategoryID { get; set; }
        public decimal VATID { get; set; }
        public decimal VATPer { get; set; }
        public Nullable<decimal> VATAmount { get; set; }
        public decimal CSTID { get; set; }
        public decimal CSTPer { get; set; }
        public Nullable<decimal> CSTAmount { get; set; }
        public decimal ServiceTaxID { get; set; }
        public decimal ServiceTaxPer { get; set; }
        public Nullable<decimal> ServiceTaxAmount { get; set; }
        public decimal ServiceTaxCessID { get; set; }
        public decimal ServiceTaxCessPer { get; set; }
        public Nullable<decimal> ServiceTaxCessAmount { get; set; }
        public decimal ServiceTaxHECessID { get; set; }
        public decimal ServiceTaxHECessPer { get; set; }
        public Nullable<decimal> ServiceTaxHECessAmount { get; set; }
        public Nullable<decimal> TotalValue { get; set; }
        public decimal StockValue { get; set; }
        public int StatusM_UID { get; set; }
        public int IsReceipt { get; set; }
        public decimal BalanceQty { get; set; }
        public decimal QtyDC { get; set; }
        public decimal QtyReceived { get; set; }
        public decimal QtyRejected { get; set; }
        public decimal CategoryM_UID { get; set; }
        public Nullable<decimal> Sales_AccountM_UID { get; set; }
        public Nullable<decimal> Stock_AccountM_UID { get; set; }
        public decimal Consumption_AccountM_UID { get; set; }
        public decimal ConversionUOM_UID { get; set; }
        public decimal ConversionUOM_Rate { get; set; }
        public decimal ConversionUOM_Qty { get; set; }
        public decimal PartyMItemsMPrice_UID { get; set; }
        public Nullable<System.DateTime> WarrantyUpto { get; set; }
        public string AdditionalInformation { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string BatchNumber { get; set; }
        public decimal MasterMRejection_UID { get; set; }
        public decimal StockRate { get; set; }
        public decimal W_Rate { get; set; }
        public decimal Rec_Qty { get; set; }
        public decimal Iss_Qty { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public bool IsValuated { get; set; }
        public int UnderDocumentTypeM_UID { get; set; }
        public decimal RefStockTransreceivedItems_UID { get; set; }
        public decimal FatPercentage { get; set; }
        public Nullable<decimal> FatRate { get; set; }
        public bool IsTemplate { get; set; }
        public Nullable<decimal> TemplateM_UID { get; set; }
        public decimal SurchargeID { get; set; }
        public decimal SurchargePer { get; set; }
        public Nullable<decimal> SurchargeAmt { get; set; }
        public System.DateTime BatchDate { get; set; }
        public decimal TareWeight { get; set; }
    }
}
