//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCheckTran
    {
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal AccountMGroups_UID { get; set; }
        public int FinYear { get; set; }
        public int DocumentTypeM_UID { get; set; }
        public string DocumentNumber { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public decimal StatusM_UID { get; set; }
        public string LongDocumentNo { get; set; }
        public string AdditionalInformation { get; set; }
        public decimal CreatedUser_UID { get; set; }
        public decimal ModifyUser_UID { get; set; }
    }
}
