//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTransReceivedItem
    {
        public decimal UID { get; set; }
        public decimal StockTrans_UID { get; set; }
        public decimal Items_UID { get; set; }
        public decimal UOM_UID { get; set; }
        public decimal Qty { get; set; }
        public decimal BalanceQty { get; set; }
        public int IsAuxllaryItem { get; set; }
        public decimal RefOrderTransList_UID { get; set; }
    }
}
