//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockValuationType
    {
        public int StockValuationTypeID { get; set; }
        public string StockValuationType1 { get; set; }
        public string StockValuationTypeDesc { get; set; }
        public bool IsActive { get; set; }
        public bool NeedPrint { get; set; }
    }
}
