//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubGroup_ImageMapping
    {
        public decimal UID { get; set; }
        public decimal SubGroupUID { get; set; }
        public string SubGroupImageName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string SubGroupLanguageName { get; set; }
        public Nullable<decimal> OrderNo { get; set; }
    }
}
