//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncBillTrans_TaxLinkList
    {
        public decimal UID { get; set; }
        public decimal BillTrans_TaxLinkList_UID { get; set; }
        public System.DateTime SyncCreatedDate { get; set; }
        public System.DateTime SyncModifiedDate { get; set; }
    }
}
