//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableTransferMemoQueue
    {
        public decimal UID { get; set; }
        public decimal KOTTrans_UID { get; set; }
        public string CurrentTableName { get; set; }
        public string NewTableName { get; set; }
        public string ItemsList { get; set; }
        public string HistoryList { get; set; }
        public string Reason { get; set; }
        public System.DateTime ChangedTime { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
