//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableListM
    {
        public decimal TableUID { get; set; }
        public string TableType { get; set; }
        public string TableName { get; set; }
        public decimal SortOrder { get; set; }
        public string DeleteConditionStr { get; set; }
        public string SyncConditionStr { get; set; }
        public bool TriggerDisableNeeded { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
