//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableM()
        {
            this.KOTTrans = new HashSet<KOTTran>();
            this.Shift_Waiter_TableLink = new HashSet<Shift_Waiter_TableLink>();
        }
    
        public decimal UID { get; set; }
        public string TableCode { get; set; }
        public string TableName { get; set; }
        public decimal AccountM_UID { get; set; }
        public bool IsAc { get; set; }
        public bool IsParcel { get; set; }
        public decimal CommissionPer { get; set; }
        public decimal Branch_UID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KOTTran> KOTTrans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shift_Waiter_TableLink> Shift_Waiter_TableLink { get; set; }
    }
}
