//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableM_Clean
    {
        public decimal UID { get; set; }
        public decimal TableM_UID { get; set; }
        public string Split { get; set; }
        public bool T_Status { get; set; }
        public System.DateTime BillTime { get; set; }
    }
}
