//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableReservationTran
    {
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public int FinYear { get; set; }
        public decimal DocumentNo { get; set; }
        public string LongDocumentNo { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public System.DateTime DocumentDateTime { get; set; }
        public decimal Customer_UID { get; set; }
        public string Description { get; set; }
        public decimal Hall_UID { get; set; }
        public int NoofPersons { get; set; }
        public decimal StatusM_UID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ReservationType { get; set; }
        public System.DateTime ReservedForDate { get; set; }
        public System.DateTime ReservedForDateTime { get; set; }
        public string Remarks { get; set; }
    }
}
