//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxMaster
    {
        public decimal UID { get; set; }
        public string TaxName { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public bool IsActive { get; set; }
        public decimal TaxType_UID { get; set; }
        public decimal CESS { get; set; }
        public decimal HECESS { get; set; }
    }
}
