//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Department
    {
        public tbl_Department()
        {
            this.tblTransfers = new HashSet<tblTransfer>();
        }
    
        public int DepartmentID { get; set; }
        public string Department { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<tblTransfer> tblTransfers { get; set; }
    }
}
