//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SubItemRawIndent
    {
        public int id { get; set; }
        public int SubItemId { get; set; }
        public int RawMaterialId { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public int Portion { get; set; }
    
        public virtual tbl_RawMaterials tbl_RawMaterials { get; set; }
        public virtual tblSubItem tblSubItem { get; set; }
    }
}
