//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignRawSubItemMst
    {
        public tblAssignRawSubItemMst()
        {
            this.tblAsgnRawSubItemDets = new HashSet<tblAsgnRawSubItemDet>();
        }
    
        public int Id { get; set; }
        public int SubItemId { get; set; }
        public System.DateTime AssignDate { get; set; }
        public int Portion { get; set; }
    
        public virtual ICollection<tblAsgnRawSubItemDet> tblAsgnRawSubItemDets { get; set; }
        public virtual tblSubItem tblSubItem { get; set; }
    }
}
