//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBasePriceItem
    {
        public tblBasePriceItem()
        {
            this.tblMenuOutlets = new HashSet<tblMenuOutlet>();
        }
    
        public int BasePriceId { get; set; }
        public int CategoryId { get; set; }
        public int ItemId { get; set; }
        public decimal FullPrice { get; set; }
        public decimal HalfPrice { get; set; }
        public decimal Vat { get; set; }
        public string AcType { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual ICollection<tblMenuOutlet> tblMenuOutlets { get; set; }
    }
}
