//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategory
    {
        public tblCategory()
        {
            this.tbl_KitchenRawIndent = new HashSet<tbl_KitchenRawIndent>();
            this.tblBasePriceItems = new HashSet<tblBasePriceItem>();
            this.tblItems = new HashSet<tblItem>();
            this.tblMenuOutlets = new HashSet<tblMenuOutlet>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public string Color { get; set; }
        public string TextColor { get; set; }
    
        public virtual ICollection<tbl_KitchenRawIndent> tbl_KitchenRawIndent { get; set; }
        public virtual ICollection<tblBasePriceItem> tblBasePriceItems { get; set; }
        public virtual ICollection<tblItem> tblItems { get; set; }
        public virtual ICollection<tblMenuOutlet> tblMenuOutlets { get; set; }
    }
}
