//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDeletedetail
    {
        public int DeleteId { get; set; }
        public int DeletedetailId { get; set; }
        public int ItemId { get; set; }
        public Nullable<int> FullQty { get; set; }
        public Nullable<int> HalfQty { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> VatAmount { get; set; }
        public Nullable<decimal> Vat { get; set; }
    
        public virtual tblDeleteBillMaster tblDeleteBillMaster { get; set; }
        public virtual tblItem tblItem { get; set; }
    }
}
