//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public tblItem()
        {
            this.Nibs_HappyHours_Date = new HashSet<Nibs_HappyHours_Date>();
            this.Nibs_HappyHours_Day = new HashSet<Nibs_HappyHours_Day>();
            this.Nibs_HappyHours_Days = new HashSet<Nibs_HappyHours_Days>();
            this.Nibs_HappyHoursDates = new HashSet<Nibs_HappyHoursDates>();
            this.Nibs_Offer_Amount = new HashSet<Nibs_Offer_Amount>();
            this.Nibs_Offer_Buy_Items = new HashSet<Nibs_Offer_Buy_Items>();
            this.Nibs_Offer_Free_Items = new HashSet<Nibs_Offer_Free_Items>();
            this.tbl_KitchenRawIndent = new HashSet<tbl_KitchenRawIndent>();
            this.tblBasePriceItems = new HashSet<tblBasePriceItem>();
            this.tblDeletedetails = new HashSet<tblDeletedetail>();
            this.tblMenuOutlets = new HashSet<tblMenuOutlet>();
            this.tblBillDetails = new HashSet<tblBillDetail>();
            this.Temp_VendorBilling = new HashSet<Temp_VendorBilling>();
            this.VendorBillingItems = new HashSet<VendorBillingItem>();
        }
    
        public int ItemId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
        public string ItemImage { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> BasePriceId { get; set; }
        public bool Active { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual ICollection<Nibs_HappyHours_Date> Nibs_HappyHours_Date { get; set; }
        public virtual ICollection<Nibs_HappyHours_Day> Nibs_HappyHours_Day { get; set; }
        public virtual ICollection<Nibs_HappyHours_Days> Nibs_HappyHours_Days { get; set; }
        public virtual ICollection<Nibs_HappyHoursDates> Nibs_HappyHoursDates { get; set; }
        public virtual ICollection<Nibs_Offer_Amount> Nibs_Offer_Amount { get; set; }
        public virtual ICollection<Nibs_Offer_Buy_Items> Nibs_Offer_Buy_Items { get; set; }
        public virtual ICollection<Nibs_Offer_Free_Items> Nibs_Offer_Free_Items { get; set; }
        public virtual ICollection<tbl_KitchenRawIndent> tbl_KitchenRawIndent { get; set; }
        public virtual ICollection<tblBasePriceItem> tblBasePriceItems { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        public virtual ICollection<tblDeletedetail> tblDeletedetails { get; set; }
        public virtual ICollection<tblMenuOutlet> tblMenuOutlets { get; set; }
        public virtual ICollection<tblBillDetail> tblBillDetails { get; set; }
        public virtual ICollection<Temp_VendorBilling> Temp_VendorBilling { get; set; }
        public virtual ICollection<VendorBillingItem> VendorBillingItems { get; set; }
        public virtual tbl_Department tbl_Department { get; set; }
        public virtual tblItem tblItem1 { get; set; }
        public virtual tblItem tblItem2 { get; set; }
    }
}
