//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLedgerMaster
    {
        public tblLedgerMaster()
        {
            this.Voucher_Entry_Credit = new HashSet<Voucher_Entry_Credit>();
            this.Voucher_Entry_Debit = new HashSet<Voucher_Entry_Debit>();
        }
    
        public int LedgerMasterId { get; set; }
        public int RecordId { get; set; }
        public string LedgerName { get; set; }
        public int LedgerGroup { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> OPBalance { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public string Transfer_Type { get; set; }
    
        public virtual tblLedgerGroup tblLedgerGroup { get; set; }
        public virtual ICollection<Voucher_Entry_Credit> Voucher_Entry_Credit { get; set; }
        public virtual ICollection<Voucher_Entry_Debit> Voucher_Entry_Debit { get; set; }
    }
}
