//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLedgerCategory
    {
        public tblLedgerCategory()
        {
            this.tblLedgerGroups = new HashSet<tblLedgerGroup>();
        }
    
        public int id { get; set; }
        public string LedgerCategoryName { get; set; }
    
        public virtual ICollection<tblLedgerGroup> tblLedgerGroups { get; set; }
    }
}
