//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLedgerGroup
    {
        public tblLedgerGroup()
        {
            this.tblLedgerMasters = new HashSet<tblLedgerMaster>();
        }
    
        public int Record_Id { get; set; }
        public string LedgerGroupName { get; set; }
        public int Category { get; set; }
    
        public virtual tblLedgerCategory tblLedgerCategory { get; set; }
        public virtual ICollection<tblLedgerMaster> tblLedgerMasters { get; set; }
    }
}
