//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenuOutlet
    {
        public tblMenuOutlet()
        {
            this.VendorPrices = new HashSet<VendorPrice>();
        }
    
        public int MenuOutletId { get; set; }
        public int OutletId { get; set; }
        public int ItemId { get; set; }
        public decimal FullPrice { get; set; }
        public decimal HalfPrice { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> BasePriceId { get; set; }
    
        public virtual tblBasePriceItem tblBasePriceItem { get; set; }
        public virtual tblCategory tblCategory { get; set; }
        public virtual tblItem tblItem { get; set; }
        public virtual tblOutlet tblOutlet { get; set; }
        public virtual ICollection<VendorPrice> VendorPrices { get; set; }
    }
}
