//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOutlet
    {
        public tblOutlet()
        {
            this.NIbs_AssignOffer = new HashSet<NIbs_AssignOffer>();
            this.tblDeleteBillMasters = new HashSet<tblDeleteBillMaster>();
            this.tblMenuOutlets = new HashSet<tblMenuOutlet>();
            this.tblOperators = new HashSet<tblOperator>();
            this.tblTableMasters = new HashSet<tblTableMaster>();
            this.tblTransfers = new HashSet<tblTransfer>();
            this.tblVendors = new HashSet<tblVendor>();
            this.tblBillMasters = new HashSet<tblBillMaster>();
            this.Temp_VendorBilling = new HashSet<Temp_VendorBilling>();
            this.VendorBillingMasters = new HashSet<VendorBillingMaster>();
            this.SelesVendorAmounts = new HashSet<SelesVendorAmount>();
            this.OutletVendors = new HashSet<OutletVendor>();
            this.tblPurchaseOrderMasters = new HashSet<tblPurchaseOrderMaster>();
            this.tblTransferReturnReports = new HashSet<tblTransferReturnReport>();
        }
    
        public int OutletId { get; set; }
        public string Name { get; set; }
        public string ContactA { get; set; }
        public string ContactB { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string TinNo { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string OutletType { get; set; }
        public string UserName { get; set; }
        public bool Active { get; set; }
        public string ProfileImage { get; set; }
        public string ServiceTaxNo { get; set; }
    
        public virtual ICollection<NIbs_AssignOffer> NIbs_AssignOffer { get; set; }
        public virtual ICollection<tblDeleteBillMaster> tblDeleteBillMasters { get; set; }
        public virtual ICollection<tblMenuOutlet> tblMenuOutlets { get; set; }
        public virtual ICollection<tblOperator> tblOperators { get; set; }
        public virtual ICollection<tblTableMaster> tblTableMasters { get; set; }
        public virtual ICollection<tblTransfer> tblTransfers { get; set; }
        public virtual ICollection<tblVendor> tblVendors { get; set; }
        public virtual ICollection<tblBillMaster> tblBillMasters { get; set; }
        public virtual ICollection<Temp_VendorBilling> Temp_VendorBilling { get; set; }
        public virtual ICollection<VendorBillingMaster> VendorBillingMasters { get; set; }
        public virtual ICollection<SelesVendorAmount> SelesVendorAmounts { get; set; }
        public virtual ICollection<OutletVendor> OutletVendors { get; set; }
        public virtual ICollection<tblPurchaseOrderMaster> tblPurchaseOrderMasters { get; set; }
        public virtual ICollection<tblTransferReturnReport> tblTransferReturnReports { get; set; }
    }
}
