//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReturn
    {
        public int ReturnId { get; set; }
        public int RawMaterialId { get; set; }
        public int ReturnQuantity { get; set; }
        public string ReturnStatuss { get; set; }
        public string ReturnDescription { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int SenderOutletId { get; set; }
        public int ReciverOutletId { get; set; }
    
        public virtual tbl_RawMaterials tbl_RawMaterials { get; set; }
    }
}
