//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransferReturnReport
    {
        public int TransferReturnId { get; set; }
        public int RawMaterialId { get; set; }
        public decimal ReturnQuantity { get; set; }
        public string ReturnDescription { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public int OutletId { get; set; }
        public Nullable<int> transferid { get; set; }
    
        public virtual tbl_RawMaterials tbl_RawMaterials { get; set; }
        public virtual tblOutlet tblOutlet { get; set; }
    }
}
