//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransfer
    {
        public int TransferId { get; set; }
        public int SenderOutletId { get; set; }
        public int RawMaterialId { get; set; }
        public decimal TransferQuantity { get; set; }
        public System.DateTime TransferDate { get; set; }
        public int ReciverOutletId { get; set; }
        public int OutletId { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual tbl_RawMaterials tbl_RawMaterials { get; set; }
        public virtual tblOutlet tblOutlet { get; set; }
        public virtual tbl_Department tbl_Department { get; set; }
    }
}
