//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransRetRateDet
    {
        public int Id { get; set; }
        public int TransferReturnId { get; set; }
        public int MaterialId { get; set; }
        public decimal qty { get; set; }
        public decimal Rate { get; set; }
    
        public virtual tbl_RawMaterials tbl_RawMaterials { get; set; }
        public virtual tblTransferReturnReport tblTransferReturnReport { get; set; }
    }
}
