//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_VendorBilling
    {
        public int ID { get; set; }
        public int VendorId { get; set; }
        public int OutletId { get; set; }
        public int ItemId { get; set; }
        public int VendorPriceId { get; set; }
        public int Qty { get; set; }
        public decimal Vat { get; set; }
        public bool IskotCleared { get; set; }
        public int QtyAfterClearKot { get; set; }
        public bool IsPrinted { get; set; }
        public bool Isdispatched { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual tblOutlet tblOutlet { get; set; }
        public virtual VendorPrice VendorPrice { get; set; }
        public virtual OutletVendor OutletVendor { get; set; }
    }
}
