//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateMList
    {
        public decimal UID { get; set; }
        public decimal TemplateM_UID { get; set; }
        public decimal AccountMItems { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> QtyPer { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public decimal SalesUOM_UID { get; set; }
        public decimal Price { get; set; }
    }
}
