//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class TokenMemoQueue
    {
        public decimal UID { get; set; }
        public decimal BillTrans_UID { get; set; }
        public decimal BillNo { get; set; }
        public decimal TokenNo { get; set; }
        public Nullable<decimal> StatusM_UID { get; set; }
        public int TokenGenerationType { get; set; }
    }
}
