//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public bool Active { get; set; }
    
        public virtual Unit Units1 { get; set; }
        public virtual Unit Unit1 { get; set; }
    }
}
