//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadDataM
    {
        public decimal UID { get; set; }
        public string ITEMCODE { get; set; }
        public string ITEMNAME { get; set; }
        public string CATEGORY { get; set; }
        public string SUBGROUPNAME { get; set; }
        public string DINEGROUPNAME { get; set; }
        public string UOM { get; set; }
    }
}
