//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FormIssuedDetails
    {
        public Nullable<bool> Selected { get; set; }
        public decimal Partners_UID { get; set; }
        public string Party { get; set; }
        public decimal UID { get; set; }
        public decimal StockTrans_UID { get; set; }
        public decimal Form_UID { get; set; }
        public string FormNumber { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public bool IsIssued { get; set; }
        public string LongDocumentNo { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string FormType { get; set; }
        public decimal TotalValue { get; set; }
    }
}
