//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VATConfiguration
    {
        public decimal UID { get; set; }
        public decimal VAT_UID { get; set; }
        public decimal VAT_AccountM_UID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public decimal MinValue { get; set; }
        public decimal MaxValue { get; set; }
        public int CalculateforType { get; set; }
        public int SerialNo { get; set; }
    }
}
