//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorPrice
    {
        public VendorPrice()
        {
            this.Temp_VendorBilling = new HashSet<Temp_VendorBilling>();
        }
    
        public int VendorPriceId { get; set; }
        public int MenuOutletId { get; set; }
        public decimal Price { get; set; }
        public int VendorId { get; set; }
    
        public virtual tblMenuOutlet tblMenuOutlet { get; set; }
        public virtual ICollection<Temp_VendorBilling> Temp_VendorBilling { get; set; }
        public virtual OutletVendor OutletVendor { get; set; }
    }
}
