//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorBillingItem
    {
        public int OrderItemId { get; set; }
        public int ItemId { get; set; }
        public decimal Amount { get; set; }
        public decimal Vat { get; set; }
        public int OrderId { get; set; }
        public int Quantity { get; set; }
    
        public virtual tblItem tblItem { get; set; }
        public virtual VendorBillingMaster VendorBillingMaster { get; set; }
    }
}
