//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_Container
    {
        public decimal UID { get; set; }
        public string SerialNumber { get; set; }
        public int Type { get; set; }
        public string ContainerType { get; set; }
        public decimal Weight { get; set; }
        public Nullable<System.DateTime> Effect_From { get; set; }
        public string Remarks { get; set; }
    }
}
