//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_ItemsRawMaterialsItems
    {
        public decimal UID { get; set; }
        public decimal AccountM_UID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string LongItemName { get; set; }
        public string ItemUOM { get; set; }
        public string AdditionalDetails { get; set; }
        public string ItemGroup { get; set; }
        public string ItemSubGroup { get; set; }
        public decimal UOM_UID { get; set; }
        public decimal Category_UID { get; set; }
        public decimal Group_UID { get; set; }
        public decimal SubGroup_UID { get; set; }
        public decimal MOQ { get; set; }
        public decimal AccountMItemsList_UID { get; set; }
        public decimal Branch_UID { get; set; }
        public decimal AccountMItems_UID { get; set; }
        public decimal QOH { get; set; }
        public decimal ROL { get; set; }
        public decimal MaximumOrderQty { get; set; }
        public decimal ConQty_PerDay { get; set; }
        public string Location { get; set; }
        public decimal Avgprice { get; set; }
        public decimal LeadTime { get; set; }
        public decimal Tolerance { get; set; }
    }
}
