//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_VendorsDetails
    {
        public decimal UID { get; set; }
        public decimal AccountM_UID { get; set; }
        public string PartnerCode { get; set; }
        public string PartnerName { get; set; }
        public string LongPartnerName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public string PinCode { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string TINNo { get; set; }
        public string TINDate { get; set; }
        public string CSTNo { get; set; }
        public string CSTDate { get; set; }
        public string PANNo { get; set; }
        public bool IsHoldForOrder { get; set; }
        public string IsHoldForOrderReason { get; set; }
        public decimal TaxTypeId { get; set; }
    }
}
