//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher_Entry_Debit
    {
        public decimal voucher_entry_id { get; set; }
        public string voucher_no { get; set; }
        public System.DateTime voucher_date { get; set; }
        public string record_no { get; set; }
        public System.DateTime record_date { get; set; }
        public decimal voucher_sno { get; set; }
        public string voucher_tb { get; set; }
        public int voucher_ledger_accout_id { get; set; }
        public decimal voucher_dbt_amount { get; set; }
        public string voucher_type { get; set; }
        public string voucher_year { get; set; }
        public string check_no { get; set; }
        public Nullable<System.DateTime> check_date { get; set; }
        public Nullable<System.DateTime> bank_date { get; set; }
        public System.DateTime create_date { get; set; }
        public int userid { get; set; }
        public string from_form_name { get; set; }
        public int from_form_id { get; set; }
        public string voucher_narration { get; set; }
        public string account_type { get; set; }
    
        public virtual tblLedgerMaster tblLedgerMaster { get; set; }
    }
}
