//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_MaterialRequest
    {
        public decimal UID { get; set; }
        public decimal Branch_UID { get; set; }
        public int FinYear { get; set; }
        public string DocumentNumber { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public System.DateTime SystemDate { get; set; }
        public decimal Partners_UID { get; set; }
        public string PartnerName { get; set; }
        public decimal StatusM_UID { get; set; }
        public string StatusReason { get; set; }
        public string LongDocumentNo { get; set; }
        public string AdditionalInformation { get; set; }
        public decimal OrderTransList_UID { get; set; }
        public decimal Items_UID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public int OrderTransList_StatusM_UID { get; set; }
        public Nullable<decimal> BalanceQty { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string OrderTransList_AdditionalInformation { get; set; }
        public string ItemUOM { get; set; }
        public string LongItemName { get; set; }
    }
}
