//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GetDevicePrintConfiguration
    {
        public Nullable<decimal> LoginHall_UID { get; set; }
        public Nullable<decimal> PrintHall_UID { get; set; }
        public string KOTPrinterName { get; set; }
        public Nullable<decimal> Branch_UID { get; set; }
        public string ServiceReqPrinter { get; set; }
        public string TakeAwayPrinterName { get; set; }
        public string BillPrinterName { get; set; }
        public string DuplicateKOTPrinterName { get; set; }
        public string DuplicateTakeAwayPrinterName { get; set; }
        public string CashDrawerPrinter { get; set; }
        public string TableTransferPrinter { get; set; }
        public string ShelfItemPrinter { get; set; }
        public string IsParcelPrinter { get; set; }
        public string CashReceiptPrinter { get; set; }
        public string BillPrintCount { get; set; }
        public string KOTPrintCount { get; set; }
        public string ServReqCount { get; set; }
        public string TakeAwayCount { get; set; }
        public string AlterKotCount { get; set; }
        public string CashRecptCount { get; set; }
        public string CashDrawCount { get; set; }
        public string ShelfPrntCount { get; set; }
        public string IsParcelCount { get; set; }
        public string AlterTakeCount { get; set; }
        public string TableTrnsCount { get; set; }
    }
}
