//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GetPayMentDetails
    {
        public decimal UID { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Card { get; set; }
        public Nullable<decimal> Voucher { get; set; }
        public Nullable<decimal> NonChargeable { get; set; }
    }
}
