//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_GetLastOrderDetails
    {
        public decimal Table_UID { get; set; }
        public System.DateTime OrderTime { get; set; }
        public string ItemName { get; set; }
        public decimal Value { get; set; }
        public string TableSplit { get; set; }
    }
}
