//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MISPartyOrderData_BillNumber
    {
        public decimal Branch_UID { get; set; }
        public int FinancialBillYear { get; set; }
        public Nullable<int> BillYear { get; set; }
        public Nullable<int> BillMonth { get; set; }
        public Nullable<int> BillWeek { get; set; }
        public Nullable<int> BillDay { get; set; }
        public decimal BillTrans_UID { get; set; }
        public decimal BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillTime { get; set; }
        public int DocumentTYpeM_UID { get; set; }
        public string BillType { get; set; }
        public decimal StatusM_UID { get; set; }
        public decimal Total { get; set; }
        public decimal NettValue { get; set; }
        public decimal CollectedAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> GrossValue { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public decimal Advance { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public decimal Discount { get; set; }
        public string Waiter { get; set; }
        public decimal KOTTrans_UID { get; set; }
        public string PartnerName { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryTime { get; set; }
        public string BillStatus { get; set; }
    }
}
