//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MISBilllingData
    {
        public decimal Branch_UID { get; set; }
        public decimal BillTrans_UID { get; set; }
        public Nullable<int> BillDay { get; set; }
        public Nullable<int> BillMonth { get; set; }
        public Nullable<int> FinancialBillYear { get; set; }
        public Nullable<int> BillYear { get; set; }
        public Nullable<int> BillTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal Qty { get; set; }
        public decimal Value { get; set; }
        public string ItemName { get; set; }
        public string ItemCode { get; set; }
        public decimal AccountMItems_UID { get; set; }
        public System.DateTime BillDate { get; set; }
    }
}
