//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MISBilllingData_TaxBillNo
    {
        public decimal Branch_UID { get; set; }
        public int FinancialBillYear { get; set; }
        public Nullable<int> BillYear { get; set; }
        public Nullable<int> BillMonth { get; set; }
        public Nullable<int> BillWeek { get; set; }
        public Nullable<int> BillDay { get; set; }
        public decimal BillTrans_UID { get; set; }
        public decimal BillNo { get; set; }
        public System.DateTime BillDate { get; set; }
        public string BillTime { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal Table_UID { get; set; }
        public string BillType { get; set; }
        public int DocumentTypeM_UID { get; set; }
        public decimal StatusM_UID { get; set; }
        public decimal NettValue { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> GrossValue { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Card { get; set; }
        public Nullable<decimal> Voucher { get; set; }
        public Nullable<decimal> Nonchargeable { get; set; }
        public Nullable<decimal> TCash { get; set; }
        public Nullable<decimal> TCard { get; set; }
        public Nullable<decimal> TVoucher { get; set; }
        public Nullable<decimal> TNonchargeable { get; set; }
        public int Advance { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public decimal Discount { get; set; }
        public int NoOfPersons { get; set; }
        public string TableName { get; set; }
        public Nullable<decimal> Tax_UID { get; set; }
        public decimal TaxPercent { get; set; }
        public decimal BTaxAmount { get; set; }
        public decimal ServiceTax_UID { get; set; }
        public decimal ServiceTaxPer { get; set; }
        public decimal EDPer { get; set; }
        public decimal HECessPer { get; set; }
        public decimal ServiceTaxAmount { get; set; }
        public decimal EDAmount { get; set; }
        public decimal HECessAmount { get; set; }
    }
}
