//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MISSalesData_ByServiceItem
    {
        public decimal Branch_UID { get; set; }
        public Nullable<int> FinancialBillYear { get; set; }
        public Nullable<int> BillYear { get; set; }
        public Nullable<int> BillMonth { get; set; }
        public Nullable<int> BillWeek { get; set; }
        public Nullable<int> BillDay { get; set; }
        public decimal BillTrans_UID { get; set; }
        public string DocumentNumber { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string BillTime { get; set; }
        public decimal BasicValue { get; set; }
        public decimal Advance { get; set; }
        public decimal Discount { get; set; }
        public Nullable<decimal> NettValue { get; set; }
        public string CollectionType { get; set; }
        public string DocumentType { get; set; }
        public decimal StatusM_UID { get; set; }
        public int DocumentTypeM_UID { get; set; }
        public int PaymentType_UID { get; set; }
        public decimal TemplateM_UID { get; set; }
        public decimal Items_UID { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public decimal TotalValue { get; set; }
    }
}
