//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MISBilllingData_BillNumber
    {
        public decimal Branch_UID { get; set; }
        public int FinancialBillYear { get; set; }
        public Nullable<int> BillYear { get; set; }
        public Nullable<int> BillMonth { get; set; }
        public Nullable<int> BillWeek { get; set; }
        public Nullable<int> BillDay { get; set; }
        public decimal BillTrans_UID { get; set; }
        public decimal BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string BillTime { get; set; }
        public int DocumentTYpeM_UID { get; set; }
        public string BillType { get; set; }
        public decimal StatusM_UID { get; set; }
        public decimal NettValue { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> GrossValue { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> Cash { get; set; }
        public Nullable<decimal> Card { get; set; }
        public Nullable<decimal> Voucher { get; set; }
        public Nullable<decimal> Nonchargeable { get; set; }
        public int TCash { get; set; }
        public int TCard { get; set; }
        public int TVoucher { get; set; }
        public int TNonchargeable { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public decimal Discount { get; set; }
        public int NoOfPersons { get; set; }
        public int TableName { get; set; }
        public Nullable<decimal> FNonchargeable { get; set; }
    }
}
