//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwAccountGroupLevel
    {
        public string AccountName { get; set; }
        public string ParentAccount { get; set; }
        public decimal AccountMGroups_UID { get; set; }
        public decimal AccountM_UID { get; set; }
        public bool IsGroup { get; set; }
        public decimal ParentAccountM_UID { get; set; }
    }
}
