//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBillMst
    {
        public System.DateTime BillDate { get; set; }
        public decimal Total { get; set; }
        public Nullable<decimal> taxamount { get; set; }
        public int serviceChrge { get; set; }
        public decimal Discount { get; set; }
        public decimal NettValue { get; set; }
        public string tableNo { get; set; }
        public int outlet { get; set; }
        public string Description { get; set; }
        public decimal BillNo { get; set; }
        public string address { get; set; }
        public string paymenttype { get; set; }
        public string chqno { get; set; }
        public string chqdate { get; set; }
        public Nullable<int> disPer { get; set; }
        public string contactNo { get; set; }
        public decimal packingChags { get; set; }
        public int Servicetax { get; set; }
        public int isprnt { get; set; }
        public Nullable<decimal> befDisc { get; set; }
        public decimal UID { get; set; }
    }
}
