//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMasters_Documents
    {
        public decimal UID { get; set; }
        public string AccountCode { get; set; }
        public string Description { get; set; }
        public int AccountType { get; set; }
        public bool IsAccount { get; set; }
        public string ShortDescription { get; set; }
        public string PrintDescription { get; set; }
        public bool IsGroup { get; set; }
        public decimal Percentage { get; set; }
        public bool IsHall { get; set; }
    }
}
