//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMasters_TransactionsDocuments
    {
        public decimal UID { get; set; }
        public decimal AccountM_UID { get; set; }
        public decimal UnderAccountM_UID { get; set; }
        public string Description { get; set; }
        public string ShortName { get; set; }
        public string PrintDescription { get; set; }
        public int AccountGroupType { get; set; }
        public int HLevel { get; set; }
        public bool IsMainHead { get; set; }
        public bool IsFixed { get; set; }
        public int Sortorder { get; set; }
        public string AccountDescription { get; set; }
    }
}
