//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwStockTransactionsKitchen
    {
        public System.DateTime Date { get; set; }
        public int MaterialId { get; set; }
        public decimal inQty { get; set; }
        public Nullable<decimal> inVal { get; set; }
        public decimal outQty { get; set; }
        public Nullable<decimal> outVal { get; set; }
        public string Remarks { get; set; }
        public int ord { get; set; }
    }
}
