//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NibsMVC.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Waiter_Dept_MappingOption
    {
        public decimal UID { get; set; }
        public decimal AccountM_UID { get; set; }
        public bool IsNeeded { get; set; }
        public bool DeviceNeeded { get; set; }
        public bool ServiceTaxNeeded { get; set; }
        public Nullable<decimal> ServiceTaxPortionByAmt { get; set; }
        public Nullable<decimal> ServiceTaxPortionByPer { get; set; }
        public bool ServiceChargeNeeded { get; set; }
        public decimal ServiceChargePer { get; set; }
    }
}
